### ISSUE TITLE
makefile gerado por makeMe_onAll

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#10]
Acrescentar um target antes de todos, que roda com `make` sem target, para listar (echo) os targets disponiveis.

**Comment by 0e1** [comment]
Existe o target `info`, exemplo, no preserv-BR: https://github.com/digital-guard/preserv-BR/blob/main/src/makefile

**Comment by ppKrauss** [comment]
ok

**Comment by ppKrauss** [comment]
REABRINDO: mais um problema, o makefile gerado em todos está com defeito, pois da mesma forma o `make` precisaria indicar a lista de targets e não fazer nada. Por hora corre risco de destruir README e não mostra a lista de targets.

Exemplo: ao rodar `make` no servidor, em  `/opt/gits/_dg/preserv-BR/data/AC/RioBranco/_pk046`.
