### ISSUE TITLE
Publicação de layer com múltiplos arquivos

### ISSUE THREAD

**Issue by 0e1** [digital-guard/preserv#101]
Conforme https://github.com/digital-guard/preserv-BR/issues/71#issuecomment-1091762131 ingestão e publicação de layers com múltiplos arquivos estão fora de compasso.

Tempos atrás, quando a ingestão de múltiplos arquivos por layer foi implantada, se decidiu por ingerir os arquivos separadamente. Em outras palavras, para cada arquivo é feita uma chamada da any_load, assim, para cada arquivo é gerado 1 id na tabela ingest.donated_packcomponent. 

Por outro lado, a publicação espera 1 id por layer.

Resumo:
Ingestão de múltiplos arquivos por layer:
- ocasiona mais de 1 id por layer na tabela ingest.donated_packcomponent;

Publicação:
- espera apenas 1 id por layer na tabela ingest.donated_packcomponent 

Decisão a tomar:
1. Fazer a ingestão de múltiplos arquivos em apenas 1 id, ou
2. Fazer a publicação trabalhar com multiplos id por layer

**Comment by 0e1** [comment]
Ok, seguimos o item 1.

...

Duas situações envolvendo ingestão de múltiplos arquivos:
1. Um sha256 contendo arquivos com string comum aos nomes ;
     a. [BR/SP/SaoPaulo/_pk0033.01](https://github.com/digital-guard/preserv-BR/blob/main/data/SP/SaoPaulo/_pk0033.01/make_conf.yaml)
     b. [CO/_pk0003.01](https://github.com/digital-guard/preserv-CO/blob/main/data/_pk0003.01/make_conf.yaml)
3. Um sha256 com arquivos com nome disjuntos informados via array:
    a. [BR/PR/Araucaria/_pk0061.01](https://github.com/digital-guard/preserv-BR/blob/main/data/PR/Araucaria/_pk0061.01/make_conf.yaml)
    b. [BR/SC/Joinville/_pk0035.01](https://github.com/digital-guard/preserv-BR/blob/main/data/SC/Joinville/_pk0035.01/make_conf.yaml)

Até aqui os dois commits anteriores tratam a situação 1 usando as opções [-p](https://manpages.debian.org/testing/postgis/shp2pgsql.1.en.html#p) e [-a](https://manpages.debian.org/testing/postgis/shp2pgsql.1.en.html#a) de _shp2pgsql_, um dos arquivos é usado para criar a tabela e, na sequencia, os dados de todos os arquivos são carregados. A estrutura de cada arquivo deve ser igual. 

No momento a ingestão de 1.a. está sendo feita, com a intenção de testar a ingestão e a publicação de, nesse caso, 1,6 milhão de dados.

**Comment by 0e1** [comment]
> 2\. Um sha256 com arquivos com nome disjuntos informados via array:
>         a. [BR/PR/Araucaria/_pk0061.01](https://github.com/digital-guard/preserv-BR/blob/main/data/PR/Araucaria/_pk0061.01/make_conf.yaml)
>         b. [BR/SC/Joinville/_pk0035.01](https://github.com/digital-guard/preserv-BR/blob/main/data/SC/Joinville/_pk0035.01/make_conf.yaml)

Sobre a situação 2: 

Quandos os arquivos tem estruturas diferentes não podemos usar o `sql_select` diretamente, uma vez que a any_load o usa internamente.

Então, eu acho que os `sql_select` presentes no array precisam ser compatibilizados, possuindo a mesma quantidade de elementos e a posição de cada elemento, por exemplo da que corresponde a _house_number_, corresponder em cada array, para que seja possível gerar tabelas para cada arquivo, uni-las e então passar para a any_load.

Não vejo motivo para a compatibilização ser feita via software, acho que deve ser manual, diretamente no yaml.

Exemplo em 2.b de sql_select:
`sql_select: [['gid', '___logradour', '___numero_25', '___bairro_28 AS ns_name', 'uso', 'geom'],['gid', 'iq_lote', 'geom']]`


Observação: aqui estão as regras, quando foi implantada a possibilidade de usar array em `sql_select` e `orig_filename`: https://github.com/digital-guard/preserv-BR/issues/24#issuecomment-1010627483. Notar que entre as regras não está a que mencionei agora, mas acho que deveria.

**Comment by crebollobr** [comment]
https://github.com/digital-guard/preserv-BR/issues/75

**Comment by crebollobr** [comment]
https://github.com/digital-guard/preserv-BR/issues/74

**Comment by 0e1** [comment]
Ingestão de múltiplos arquivos está funcional.

Resumo de como funciona: independentemente da situação _any_load_ é executada para cada arquivo. No entanto, o primeiro id gerado (na ingestão do primeiro arquivo) é reutilizado na a ingestão dos demais arquivos. Isso é feito passando como referencia o mesmo arquivo para todas as chamadas da _any_load_, possibilitando recuperar o id a cada chamada da _any_load_, subsequente a primeira chamada.

@ppKrauss Com isso a ingestão é feita de um em um, melhorando o uso dos recursos .

@crebollobr Você já pode testar e gerar as publicações de

- [BR/SP/SaoPaulo/_pk0033.01](https://github.com/digital-guard/preserv-BR/blob/main/data/SP/SaoPaulo/_pk0033.01/make_conf.yaml)
- [BR/SC/Joinville/_pk0035.01](https://github.com/digital-guard/preserv-BR/blob/main/data/SC/Joinville/_pk0035.01/make_conf.yaml)

Minhas recomendações:
- Usar uma _ingest_ nova;
- Sobre São Paulo:
  - fazer a ingestão por layer, ao invés de usar _all_layers_.

Quanto à [BR/PR/Araucaria/_pk0061.01](https://github.com/digital-guard/preserv-BR/blob/main/data/PR/Araucaria/_pk0061.01/make_conf.yaml) a ingestão depende da resolução de https://github.com/digital-guard/preserv/issues/102 . Como isso me parece estar relacionado a problemas nos dados e não a ingestão de múltiplos arquivos, fecho essa issue.
