### ISSUE TITLE
Adicionar scope na Donated_PackTpl

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#109]
Ver https://github.com/digital-guard/preserv/blob/main/docs/pt/specUML.md

Foi uma falha não termos vinculado ao pacote, é pelo  atributo scope do pacote que se faz o recorte limitando os dados filtrados.

**Comment by 0e1** [comment]
[donatedPack.csv](https://github.com/digital-guard/preserv-BR/blob/main/data/donatedPack.csv) já possui uma coluna chamada `escopo`.

Então, seria o seguinte
1. Mudar o nome de `escopo` para `scope` em [donatedPack.csv](https://github.com/digital-guard/preserv-BR/blob/main/data/donatedPack.csv);
2. Alterar o software para obter a geometria da jurisdição a partir da string citada em `scope`;
3. Excluir scope_osm_id em [donor.csv](https://github.com/digital-guard/preserv-BR/blob/main/data/donor.csv);
4. Alterar o nome de kx_scope_label para scope_label em [donor.csv](https://github.com/digital-guard/preserv-BR/blob/main/data/donor.csv);
5. Alterar o software onde for necessário;
6.  Testar algumas ingestões, pra ver se tudo bem.

?

**Comment by ppKrauss** [comment]
> Então, seria o seguinte (...) ?

Exato. Mais um item: anote todos os impactos pois vamos fazer mais alterações em donatedPack essa semana, depois de clarificar  [preserv-BR/issues/82](https://github.com/digital-guard/preserv-BR/issues/82)

----

Outras issues afins: #106

**Comment by 0e1** [comment]
Implementado. 
@crebollobr , utilizar uma base _ingest_ nova.
