### ISSUE TITLE
make com multiplos usuários

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#11]
Por exemplo `make openstreetmap` em [_pk004 da Colômbia](https://github.com/digital-guard/preserv-CO/tree/main/data/_pk004) rodou primeiro com um usuário que depois fez DROP da base, depois com um usuário que queria rodar aproveitando o que já baixou... 

**Sugetão**: criar targetX que roda com `sudo make targetX` executando todos os chmods e chowns necessários.

```
rm: cannot remove '/tmp/sandbox/_pk4_001/b82a7ab85d2cb4342d51b7ab97e74be291a57c9f35001bf827d1226527449ca2.pbf': Permission denied
cd /tmp/sandbox/_pk4_001;  cp  /var/www/preserv.addressforall.org/download/b82a7ab85d2cb4342d51b7ab97e74be291a57c9f35001bf827d1226527449ca2.pbf . ; chmod -R a+rx . > /dev/null
cp: cannot create regular file './b82a7ab85d2cb4342d51b7ab97e74be291a57c9f35001bf827d1226527449ca2.pbf': Permission denied
chmod: changing permissions of '.': Operation not permitted
chmod: changing permissions of './b82a7ab85d2cb4342d51b7ab97e74be291a57c9f35001bf827d1226527449ca2.pbf': Operation not permitted
make: *** [makefile:47: openstreetmap] Error 1
/opt/gits/_dg/preserv-CO/data/_pk004$ psql postgres://postgres@localhost
```

**Comment by 0e1** [comment]
Acho que esse https://github.com/digital-guard/preserv/commit/30a18807bc76c741973a02cf4de7545ba77cde38 e esse https://github.com/digital-guard/preserv/commit/75bf8609c9fea813a88b6a3cf44f5167e9250e24 resolvem esses problemas.

**Comment by ppKrauss** [comment]
@crebollobr testar e fechar issue se tudo ok.
