### ISSUE TITLE
planilha jurisdictionLevel8

### ISSUE THREAD

**Issue by luisfelipebr** [digital-guard/preserv#113]
Adicionei CE (Fortaleza) no preserv-BR, mas não sei onde encontrar a planilha jurisdictionLevel8 completa. @0e1 você pode me ajudar? Segue sugestão do @ppKrauss :

"precisamos gerar o CSV com PostgREST, visto que só a base online agrega todos os CSVs dos gits"

**Comment by 0e1** [comment]
@luisfelipebr, nova api.

Agora o _tabelão_ pode ser consultado com:

`curl "http://localhost:3103/stats_donated_packcomponent"` obtendo como resultado um json,

ou com

`curl "http://localhost:3103/stats_donated_packcomponent" -H "Accept: text/csv"`.

para obter no formato csv.

Para gerar um arquivo, redirecionar a saída com `>`:

`curl "http://localhost:3103/stats_donated_packcomponent" -H "Accept: text/csv" > stats.csv`

obtendo um arquivo chamado _stats.csv_ no diretório corrente.

Novamente, os operadores descritos em https://postgrest.org/en/stable/api.html podem ser utilizados para estreitar o resultado da consulta.

Por exemplo, para obter os pacotes com origem _via email_, podemos utilizar o operador `like` e o campo `uri_objtype`:

`curl "http://localhost:3103/stats_donated_packcomponent?uri_objtype=like.*email*" -H "Accept: text/csv" > stats_pack_from_email.csv`

obtendo um arquivo chamado `stats_pack_from_email.csv` com os pacotes que possuem a string _email_ no campo `uri_objtype`.

**Comment by ppKrauss** [comment]
@0e1 , as tabelas de dados públicos poderão ter também uma URL pública do tipo `osm.codes/_sql/{query}`, ou seja, dispensariam ter acesso SSH ao servidor.

**Comment by ppKrauss** [comment]
@0e1 estamos aguardando o endereço público dessas queries.

**Comment by 0e1** [comment]
Aqui as apis relacionadas:

- Jurisdições:
  https://osm.codes/_sql/jurisdiction

- Union de fdw_donor de todas as jurisdições:
  https://osm.codes/_sql/donors

- Union de fdw_donatedpack X fdw_donor de todas as jurisdições:
  https://osm.codes/_sql/donatedpacks_donor

- Tabelão:
  https://osm.codes/_sql/stats_donated_packcomponent

- Para gráfico donor_status X number of donors:
  https://osm.codes/_sql/stats_donors_prospection

- Para gráfico layers X packages:
  https://osm.codes/_sql/stats_donated_packcomponent_classgrouped

- Para gráfico donated packages X date:
  https://osm.codes/_sql/stats_donated_pack_timeline

- Para tabela de licenças:
  https://osm.codes/_sql/stats_donated_pack_licensegrouped

**Comment by luisfelipebr** [comment]
Todos os links funcionando
