### ISSUE TITLE
Incluir processamento do elongation_factor e UPDATEs

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#116]
Ver https://github.com/osm-codes/WS/issues/11

**Comment by 0e1** [comment]
As views citadas na issue foram adicionadas em [optim-step6-metrics](https://github.com/digital-guard/preserv/blob/main/src/optim-step6-metrics.sql).

Os updates devem ser realizados sempre que novas geometrias forem adicionadas na tabela de jurisdições.

Em [man-updateJurisd](https://github.com/digital-guard/preserv/blob/main/docs/pt/man-updateJurisd.md) estão os passos para trabalhar em [optim.jurisdiction](https://github.com/digital-guard/preserv/blob/main/src/optim-step1-ini.sql#L9) e [optim.jurisdiction_geom](https://github.com/digital-guard/preserv/blob/main/src/optim-step1-ini.sql#L52).

Issues associadas: https://github.com/osm-codes/WS/issues/11, https://github.com/osm-codes/WS/issues/37
