### ISSUE TITLE
Importação osm2pgsql gera JSONb no primeiro passo 

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#117]
Podemos economizar tempo e CPU com a nova versão [1.5+](https://github.com/openstreetmap/osm2pgsql/releases), que [por fim](https://github.com/openstreetmap/osm2pgsql/issues/672) incorporou JSONb, ver exemplo em https://osm2pgsql.org/doc/manual.html#upgrading

**Comment by 0e1** [comment]
Interessante.

No ubuntu:
- 21.10          usa a versão 1.4.1: https://packages.ubuntu.com/impish/osm2pgsql
- 22.04 (LTS) usa a versão 1.6.0: https://packages.ubuntu.com/jammy/osm2pgsql

@crebollobr , é necessário atualizar o SO do servidor para versão LTS para usar jsonb com osm2pgsql.

**Comment by crebollobr** [comment]
Atualizado

carlos@addressforall:~$ osm2pgsql -V
2022-10-28 17:34:55  osm2pgsql version 1.6.0
Build: None
Compiled using the following library versions:
Libosmium 2.17.3
Proj [API 6] 8.2.1
Lua 5.3.6
