### ISSUE TITLE
Brasilia - Union - arquivo em repositório

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv#120]
Link: https://github.com/digital-guard/preserv-BR/tree/main/data/DF/Brasilia/_pk0068.01

Camada parcel é união. Quando faz make parcel o script está buscando o arquivo no preserv e não no download novo
```

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=C.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs DO-Regular (306F2),ASM,AES-NI)

Scanning the drive for archives:
1 file, 128753940 bytes (123 MiB)

Extracting archive: /var/www/preserv.addressforall.org/download/c9aca8c68c827c3a73598b677dc217fd8af5df1b8f53349e37b00a
e13bcd46bd.zip
--
Path = /var/www/preserv.addressforall.org/download/c9aca8c68c827c3a73598b677dc217fd8af5df1b8f53349e37b00ae13bcd46bd.zi
p
Type = zip
make: *** [makefile:155: parcel] Error 1



```

**Comment by ppKrauss** [comment]
Conferir e corrigir https://github.com/digital-guard/preserv/issues/121 se necessário

**Comment by 0e1** [comment]
Não enxerguei qual o problema.

O diretório _default_ é informado em `orig` no arquivo https://github.com/digital-guard/preserv-BR/blob/main/src/maketemplates/commomFirst.yaml. Valor atual: `orig:    /var/www/preserv.addressforall.org/download`.

Assim, se `c9aca8c68c827c3a73598b677dc217fd8af5df1b8f53349e37b00a` estiver em` /var/www/preserv.addressforall.org/download` o software vai buscar desse diretório. Se não estiver, fará o download de http://dl.digital-guard.org/c9aca8c no diretório `/var/www/preserv.addressforall.org/download`. Essa foi a lógica estabelecida. Então, sem clarear melhor a situação, o comportamento está normal.

Daí, dois caminhos:

* **não quero trocar** `orig` em https://github.com/digital-guard/preserv-BR/blob/main/src/maketemplates/commomFirst.yaml mas **quero** obter o arquivo de outro diretório:
  usar `make layer pg_db=<base> orig=<caminho absoluto do diretório que contem o arquivo>`
* **quero trocar** `orig` e usar outro diretório como _default_: 
  atualizar o valor em https://github.com/digital-guard/preserv-BR/blob/main/src/maketemplates/commomFirst.yaml


Aproveito para pedir que no momento de abertura de issue:

* informar os comandos executados;
* informar output completo dos comandos.






> Conferir e corrigir #121 se necessário

A principio, se deve fazer o seguinte:
* atualizar `orig` de _commomFirst.yaml_ em todos os repositórios (cada país tem o seu);
* criar diretório no servidor, se não existir (lembrar que é cache, não precisa mover o conteúdo de `/var/www/preserv.addressforall.org/download` se não quiser);
* conferir nginx e makefiles se não existe hardcode (a principio acho que não).

**Comment by crebollobr** [comment]
O script não fez download do arquivo.
Eu fiz download e copiei para a pasta /var/www/preserv.addressforall.org/download
O comando foi make parcel pg_db=ingest20

O Parcel é union de dois layers

**Comment by 0e1** [comment]
Exemplo do script fazendo download. Não é preciso fazer manualmente:

```sh
------------------------------------------
------ BR-DF-Brasilia  ------
------ Layer tipo parcel_full  ------
-- Incluindo dados do arquivo-2 do package-7600006801201 na base ingest99 --
 Nome-hash do arquivo-2: b55567b8f4b77e16eb7805ac2883ffed63b67ec7d39aed103e914bbea0d94750.zip
 Tabela do layer: pk7600006801201_p2_parcel
 Sub-arquivos do arquivo-2 com o conteúdo alvo: '*Lotes Registrados*' '*Lotes implantados*'
 Tema dos sub-arquivos: lotes
Run with tmux and sudo! (DANGER: seems not idempotent on psql)
claiton
Above user is root? If not, you have permissions for all paths?
[Press ENTER to continue or Ctrl+C to quit]
 File b55567b8f4b77e16eb7805ac2883ffed63b67ec7d39aed103e914bbea0d94750.zip not exists in orig=/var/www/preserv.addressforall.org/download
 Download file b55567b8f4b77e16eb7805ac2883ffed63b67ec7d39aed103e914bbea0d94750.zip to /var/www/preserv.addressforall.org/download from dl.digital-guard.org?
 If it doesn't download, inform the correct value of the orig variable.
[Press ENTER to download or Ctrl+C to quit or inform orig]
 Downloading file...
wget -P /var/www/preserv.addressforall.org/download http://dl.digital-guard.org/b55567b8f4b77e16eb7805ac2883ffed63b67ec7d39aed103e914bbea0d94750.zip
--2022-10-24 15:54:17--  http://dl.digital-guard.org/b55567b8f4b77e16eb7805ac2883ffed63b67ec7d39aed103e914bbea0d94750.zip
Resolving dl.digital-guard.org (dl.digital-guard.org)... 165.227.5.135
Connecting to dl.digital-guard.org (dl.digital-guard.org)|165.227.5.135|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://addressforall-my.sharepoint.com/personal/operacao_addressforall_org/_layouts/15/download.aspx?share=ETLOgV34SjVBpqK6I8RGI_oBepd-o8Eu1RS0oPEDJ3yr-g [following]
--2022-10-24 15:54:17--  https://addressforall-my.sharepoint.com/personal/operacao_addressforall_org/_layouts/15/download.aspx?share=ETLOgV34SjVBpqK6I8RGI_oBepd-o8Eu1RS0oPEDJ3yr-g
Resolving addressforall-my.sharepoint.com (addressforall-my.sharepoint.com)... 13.107.136.9, 13.107.138.9
Connecting to addressforall-my.sharepoint.com (addressforall-my.sharepoint.com)|13.107.136.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 124011266 (118M) [application/x-zip-compressed]
Saving to: ‘/var/www/preserv.addressforall.org/download/b55567b8f4b77e16eb7805ac2883ffed63b67ec7d39aed103e914bbea0d94750.zip’

b55567b8f4b77e16eb7805ac2883ffed63b67ec7d39a 100%[===========================================================================================>] 118.27M  31.0MB/s    in 4.9s    

2022-10-24 15:54:22 (24.3 MB/s) - ‘/var/www/preserv.addressforall.org/download/b55567b8f4b77e16eb7805ac2883ffed63b67ec7d39aed103e914bbea0d94750.zip’ saved [124011266/124011266]

```


Feito o download, o script passa a buscar o arquivo na pasta, conforme comentei na minha mensagem anterior.
