### ISSUE TITLE
Trocar antiga pasta www de download por nova

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#121]
A antiga pasta `/var/www/preserv.addressforall.org/download` passou a ser `/var/www/dl.digital-guard.org`. A mudança pode ter impacto em diversos scripts, incluindo NGINX e makefiles.

**Comment by 0e1** [comment]
@ppKrauss esse commit https://github.com/digital-guard/preserv-BR/commit/231cf489eeeaad524c94538289f9022b78511f39 sugere usar `/tmp/sandbox/downloads/` durante o processo de ingestão.

Temos duas necessidades:

1. diretório para cache do _dl.digital-guard.org_  (atualmente `/var/www/preserv.addressforall.org/download/`).
2. diretório para download de arquivos durante o processo de ingestão (atualmente o default é`/var/www/preserv.addressforall.org/download/`).

Então, podemos seguir dois caminhos:
1.  As duas necessidades podem ser atendidas pelo mesmo diretório;
2. Cada uma com o seu.

Acho que devemos seguir a segunda opção, restringindo `/tmp ou /tmp/sandbox` para evitar problemas com os arquivos baixados.

**Comment by ppKrauss** [comment]
> Então, podemos seguir dois caminhos:

Ok, uma pasta diferente para cada função é melhor. Resta documentar.
