### ISSUE TITLE
refatorar antigas pubLib e documentar dependências

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#125]
As mudanças afetam instaladorres locais (pubLib) e makefile do preserv, além das bibliotecas, **SQL-Views** e funções dependentes. A dependência entre funções, entre views, entre funções e VIEWs e MATERIALIZED, todas precisam ser documentadas em **planilha de documentação das dependências**.

Parte1 - ver instruções de movimentação em 
* https://github.com/AddressForAll/pg_pubLib-v1/blob/main/src/pubLib05hcode-distrib.sql
* https://github.com/AddressForAll/pg_pubLib-v1/blob/main/src/pubLib05hcode-encdec.sql

Parte2 - pendente generalizar https://github.com/AddressForAll/pg_pubLib-v1/blob/main/src/pubLib05pgis-geohash.sql

Parte3 - pendente decidir se move ou não, https://github.com/AddressForAll/pg_pubLib-v1/blob/main/src/pubLib05pgis-extraSRID.sql

**Comment by 0e1** [comment]
Sobre a **parte 1**:

* https://github.com/digital-guard/preserv/commit/bb40fa9ab39d0f047c5014ea534d0237c7e910f3 e https://github.com/digital-guard/preserv/commit/1887ecaca3b05b2c8036ff7d1cbf3eaa403deaa1 fazem o ajuste necessário para o processo de ingestão, que depende de funções do schema hcode.
* https://github.com/osm-codes/GGeohash/commit/43e99625543fc9e4c472f4b47a9fd3dbdde40a4b faz as atualizações em ggeohash.
  * Notar que atualizei as funções `ggeohash.encode3` e `ggeohash.decode_box2`. Foi movida versão antiga;
  * Também, troquei o nome do schema `libosmcodes` por `osmc` no _step3_;
  * Aproveitei, ainda, para reordenar as funções em _libggeohash_.
* Atualizei a `dl03t_main`, usando os novos schemas e removendo as funções antigas.
* Testei o funcionamento de http://osm.codes. Aparentemente, funcionando.

**Comment by 0e1** [comment]
Considero essa issue atendida. Por isso, vou fechá-la.
