### ISSUE TITLE
Simplificar o make, falha na obrigatoriedade de pushd

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#128]
Os comandos `pushd $path`  e `popd` **podem ser usados internamente** no *makefile*, mas **jamais ser usados como parâmetro obrigatório** do usuário... O make precisa ser amigo, não complicar a vida do usuário.

Ver exemplo de bug (não pode obrigar `pushd`) em https://github.com/digital-guard/preserv-CO/issues/16#issuecomment-1433389611

**Comment by 0e1** [comment]
> Os comandos `pushd $path` e `popd` **podem ser usados internamente** no _makefile_, mas **jamais ser usados como parâmetro obrigatório** do usuário... O make precisa ser amigo, não complicar a vida do usuário.

Não vou mais mencionar os comandos **pushd** e **popd** em respostas. Afinal, _não são obrigatórios_ e _não precisam estar no make_. Intensão era facilitar para o interlocutor, que poderia copiar e colar os comandos em qualquer terminal.

Criar outra issue se o _path_  de um pacote de dados deve ser um parâmetro opcional do _make_. Funcionalidade que não existe atualmente.



> Ver exemplo de bug (não pode obrigar `pushd`) em [digital-guard/preserv-CO#16 (comment)](https://github.com/digital-guard/preserv-CO/issues/16#issuecomment-1433389611)

Retifiquei. Ver: https://github.com/digital-guard/preserv-CO/issues/16#issuecomment-1446626733

**Comment by ppKrauss** [comment]
> facilitar para o interlocutor

Na documentação e no diálogo de Suporte, basta usar o comando `cd` universal posicionando na pasta padrão, `/var/gits`.
