### ISSUE TITLE
Incluir target delete_file para simplificar rollback

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#13]
Atualmente devido ao MD5 a recarga não é permitida. Para recarga por exemplo do arquivo 18 o procedimento é 

```sh
psql -c "DELETE FROM ingest.layer_file WHERE file_id=18" # agora com cascade implementado
```

O mesmo pode ser feito fornecendo-se o MD5 (ou like) do arquivo.

**Comment by 0e1** [comment]
Implementado aqui: https://github.com/digital-guard/preserv/commit/b4fbd4e89fc0c929fdd64f47768746456f663c38

`make delete_file hash=hash_ou_parte_inicial_do_hash`

**Comment by ppKrauss** [comment]
@crebollobr testar e fechar issue se tudo ok.

**Comment by crebollobr** [comment]
Não consegui testar #23

**Comment by ppKrauss** [comment]
Olá, qual foi o problema?

@Claiton Neisse ***@***.***> , o target foi implementado?

Em dom, 7 de nov de 2021 17:12, CARLOS REBOLLO ***@***.***>
escreveu:

**Comment by crebollobr** [comment]
Não consegui fazer o make all_layers como descrito no #23

**Comment by crebollobr** [comment]
#23 deu certo, fiz os testes de está tudo OK
