### ISSUE TITLE
make redirects_update pg_datalake=dl05s_main não está funcionando

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv#130]
```

carlos@addressforall:/var/gits/_dg/preserv/src$ make redirects_update pg_datalake=dl05s_main
mkdir -p /tmp/pg_io
-- Atualização de redirecionamentos --
--- dl.digital-guard.org ---
psql postgres://postgres@localhost/dl05s_main -c "SELECT download.insert_dldg_csv();"
ERROR:  missing data for column "filename_original"
CONTEXT:  COPY redirects_dlguard, line 718: ""
SQL statement "INSERT INTO download.redirects(donor_id,filename_original,package_path,hashedfname,hashedfnameuri)
  SELECT donor_id,filename_original,package_path,de_sha256,para_url
  FROM tmp_orig.redirects_dlguard
  ON CONFLICT (hashedfname,hashedfnameuri)
  DO UPDATE
  SET donor_id=EXCLUDED.donor_id, filename_original=EXCLUDED.filename_original, package_path=EXCLUDED.package_path
  -- RETURNING 'Ok, updated download.redirects.'"
PL/pgSQL function download.insert_dldg_csv() line 3 at SQL statement
make: *** [makefile:260: redirects_update] Error 1


```

essa linha não existe, 718

**Comment by 0e1** [comment]
Conforme o histórico https://github.com/digital-guard/preserv/commits/633ba274809bcd7e7f2205a4ac3413e2130714dc/data/redirs/fromDL_toFileServer.csv você **adicionou** e **removeu** linhas em branco ao final do arquivo. `COPY` falha se tiver linhas em branco.

Porém, você esqueceu de executar `git pull` no servidor depois de remover as linhas em branco. Atualizar o repositório no github não é suficiente. É preciso atualizar o repositório no servidor. Ver [O que fazer após atualizar fromDL_toFileServer.csv](https://wiki.addressforall.org/doc/dg:Conven%C3%A7%C3%B5es/Armazenamento_de_dados#O_que_fazer_ap%C3%B3s_atualizar_fromDL_toFileServer.csv).

Inclui na wiki avisos para **não adicionar linhas em branco** ao final dos arquivos. Ver: 
[dg:Convenções/Armazenamento de dados](https://wiki.addressforall.org/doc/dg:Conven%C3%A7%C3%B5es/Armazenamento_de_dados)
[a4a:Convenções/Visualização de dados](https://wiki.addressforall.org/doc/a4a:Conven%C3%A7%C3%B5es/Visualiza%C3%A7%C3%A3o_de_dados)
