### ISSUE TITLE
Simbolos no readme

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv#137]
https://github.com/digital-guard/preserv-BR/tree/main/data/RJ/RioJaneiro/_pk0078.02
```
> foi traduzido para &gt; 
```

![image](https://github.com/digital-guard/preserv/assets/22559999/4f7a9249-98e6-49c9-80b6-1a5c9287100f)

**Comment by crebollobr** [comment]
mais um
https://github.com/digital-guard/preserv-BR/tree/main/data/RS/PortoAlegre/_pk0018.01

**Comment by crebollobr** [comment]
https://github.com/digital-guard/preserv-BR/tree/main/data/RS/Bage/_pk0082.01

**Comment by crebollobr** [comment]
imagem cadvia não tem imagem
https://github.com/digital-guard/preserv-BR/tree/main/data/SC/Florianopolis/_pk0053.01

**Comment by crebollobr** [comment]
Tem um y `` no readme
https://github.com/digital-guard/preserv-PE/tree/main/data/CUS/Cusco/_pk0001.01

**Comment by crebollobr** [comment]
datagrid sem imagem
https://github.com/digital-guard/preserv-CO/tree/main/data/_pk0006.01

**Comment by 0e1** [comment]
> Tem um y `` no readme https://github.com/digital-guard/preserv-PE/tree/main/data/CUS/Cusco/_pk0001.01

Consertado.



> https://github.com/digital-guard/preserv-BR/tree/main/data/RJ/RioJaneiro/_pk0078.02

Consertado.



> mais um https://github.com/digital-guard/preserv-BR/tree/main/data/RS/PortoAlegre/_pk0018.01

Consertado.



> https://github.com/digital-guard/preserv-BR/tree/main/data/RS/Bage/_pk0082.01

Consertado.

**Comment by 0e1** [comment]
> imagem cadvia não tem imagem https://github.com/digital-guard/preserv-BR/tree/main/data/SC/Florianopolis/_pk0053.01



> datagrid sem imagem https://github.com/digital-guard/preserv-CO/tree/main/data/_pk0006.01


Ainda falta criar imagens para esses casos.

**Comment by 0e1** [comment]
Adicionei os ícones que faltavam em https://github.com/digital-guard/preserv/commit/7330134eeafd2763ae5ba5933cac7e685b1a2ac6.
