### ISSUE TITLE
Criar repositório do México

### ISSUE THREAD

**Issue by IgorEliezer** [digital-guard/preserv#139]
Devido a #138, precisaremos criar o repositório do México (preserv-mx).

**Comment by IgorEliezer** [comment]
Quando estiver criado, dê um @ para mim, para eu levantar a estrutura administrativa do país no OSM e completar o README.

**Comment by 0e1** [comment]
Criei o repositório. E acabei fazendo o readme.
Ainda falta eu importar as geometrias das jurisdições.

**Comment by 0e1** [comment]
Criação do repositório e inclusão das jurisdições e geometrias concluída.

Repositório em https://github.com/digital-guard/preserv-MX.

Geometrias obtidas de https://github.com/digital-guard/preserv-MX/tree/main/data/_pk0001.01.

Rascunho do trabalho necessário para incluir as geometrias disponível em https://github.com/digital-guard/preserv/wiki/Adi%C3%A7%C3%A3o-de-geometrias-jurisdicionais#caso-m%C3%A9xico
