### ISSUE TITLE
Exemplo de join de layers

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv#14]
Indicar ou enviar um exemplo de join de layers

**Comment by 0e1** [comment]
Não vi nos make_conf.yaml atuais a presença de um layer e seu respectivo layer de cadastro (por exemplo, via e cadvia).

Para testar a implementação de join que fiz, utilizei a cidade de Caxias do Sul: https://github.com/digital-guard/preserv-BR/blob/main/data/RS/CaxiasSul/_pk075/make_conf.yaml

Para fazer esse teste transformei o layer address em cadgenericvia. Resalto que fiz isso apenas para eu testar e verificar que o join esta funciona. Não commitei essa alteração nesse yaml.

O join está integrado no template ref027a: https://github.com/digital-guard/preserv/blob/main/src/maketemplates/make_ref027a.mustache.mk#L231.

A lógica descrita no link a seguir é implementada em python, no run_mustache: https://github.com/digital-guard/preserv/blob/main/docs/pt/ftypes.md.

O (sub)template que utilizo é esse https://github.com/digital-guard/preserv/blob/main/src/maketemplates/common005_join.mustache. Basicamente, esse template chama a função ingest.join em https://github.com/AddressForAll/WS/blob/master/src/ingest-step1-ini.sql#L847.

Exemplo, repito: exemplo para eu testar (cambiarra!!):
  genericvia:
    ...
    sql_select: ['gid', 'inscrica_1', 'geom']
    join_column: inscrica_1
    ...

  cadgenericvia:
    ...
    sql_select: ['cod_localizacao_completo', 'nr_imovel AS house_number']
    join_column: cod_localizacao_completo
    ...


gerar o make file com make me

e depois, pra testar o join:
make join-genericvia.

**Comment by crebollobr** [comment]
fechando issue
