### ISSUE TITLE
Corrigir links da parceria A4A-Esri

### ISSUE THREAD

**Issue by IgorEliezer** [digital-guard/preserv#140]
Sobre a wiki da parceria A4A/Esri no GitHub: temos links quebrados para acessar os readmes e baixar o shp. https://github.com/digital-guard/preserv-BR/wiki/Melhorias-OSM-pelo-preserv%E2%80%90BR

![image](https://github.com/digital-guard/preserv/assets/4673289/9d2863c3-38af-4c03-99cc-d3bae1ef55c3)

* https://git.digital-guard.org/preserv-BR/tree/main/data/ES/CachoeiroItapemirim/_pk0091.01 -> página em branco
* https://dl.digital-guard.org/out/a4a_br_es_cachoeiroitapemirim_via_7600009101601.zip -> 502 Bad Gateway

Também dei uma editada na wiki do DG para deixar os links mais visíveis: https://github.com/digital-guard/preserv-BR/wiki/Melhorias-OSM-pelo-preserv%E2%80%90BR#es-cachoeiroitapemirim.

**Comment by ppKrauss** [comment]
@IgorEliezer indicar exatamente as falhas (links que não funcionam mais) para que @0e1 possa resolver

**Comment by IgorEliezer** [comment]
@ppKrauss coloquei no 1º post.

**Comment by 0e1** [comment]
> * https://git.digital-guard.org/preserv-BR/tree/main/data/ES/CachoeiroItapemirim/_pk0091.01 -> página em branco

Corrigi o problema, relacionado ao https.


> * https://dl.digital-guard.org/out/a4a_br_es_cachoeiroitapemirim_via_7600009101601.zip -> 502 Bad Gateway

Corrigi o problema. Estava sendo usado `unix:/run/php/php8.0-fpm.sock` mas no servidor temos atualmente `/run/php/php8.1-fpm.sock`. Troquei por  `unix:/run/php/php-fpm.sock`.
Verifiquei e outros sites-avaliables não foram afetados.

Se após o teste estiver tudo funcionando, pode encerrar a issue.

**Comment by IgorEliezer** [comment]
Confirmo como corrigido.
