### ISSUE TITLE
Link do metadados do pacote ainda aponta para OSMcodes

### ISSUE THREAD

**Issue by IgorEliezer** [digital-guard/preserv#141]
O link da jurisdição no box de metadados ainda aponta para OSMcodes. Precisa mudar para https://afa.codes/*

![image](https://github.com/digital-guard/preserv/assets/4673289/ce423b55-0ad4-4591-ac6f-6f670ac8e536)

https://github.com/digital-guard/preserv-BR/tree/main/data/ES/CachoeiroItapemirim/_pk0091.01

**Comment by 0e1** [comment]
Troca efetuado nos templates e nos README atuais do preserv-BR e prevers-MX.

**Comment by IgorEliezer** [comment]
Ok. Não sei se você já ia fazer, mas dei uma olhada nos outros. Também achei em https://github.com/digital-guard/preserv-CO/tree/main/data/DC/Bogota/_pk0001.01.
