### ISSUE TITLE
Remover a coluna shortName da planilha donor.csv

### ISSUE THREAD

**Issue by IgorEliezer** [digital-guard/preserv#142]
Para simplificar o preenchimento e por redundância, foi decidido remover a coluna `shortName `da Planilha de Doadores (donor.csv). O preenchimento desta coluna requeria que o usuário abrisse outra planilha dos (5,5 mil) municípios do Brasil e manualmente buscar, copiar e colar a sigla de três letras do município, e que nem sempre está disponível. E os demais países não têm nada.

Uma versão curta do nome do doador (na coluna `legalName`) poderia ser gerado por um sistema de abreviação/abreviaturas, não precisando assim ser preenchido manualmente com base em planilhas de abreviaturas.

**Comment by 0e1** [comment]
> Para simplificar o preenchimento e por redundância, foi decidido remover a coluna `shortName `da Planilha de Doadores (donor.csv).

Implicação adicional:

- remover `donor_label` de _donatedPack.csv_, uma vez que ela referencia `shortName`.

***

Documentação/guia sobre _donor.csv_ e _donatedPack.csv_

- donor.csv:              https://wiki.addressforall.org/doc/dg:Guia_de_preenchimento_da_Planilha_de_Pacotes
- donatedPack.csv: https://wiki.addressforall.org/doc/dg:Guia_de_preenchimento_da_Planilha_de_Doadores

**Comment by 0e1** [comment]
Remoção da de `donor_label` e `shortName` concluída.

- Removi as colunas de todos os _donor.csv_ e _donatedPack.csv_;
- Removi do código.
