### ISSUE TITLE
Duplicação em fromDL_toFileServer.csv 

### ISSUE THREAD

**Issue by 0e1** [digital-guard/preserv#149]
Arquivo **b18fc8ebe8bccc2cfdbbbd5f4896d5f6573033ebfa80061d1d86550c5ae8521d.zip** informado duas vezes em  [fromDL_toFileServer.csv](https://github.com/digital-guard/preserv/blob/49c8f8065d9294e3aba1ffa5f50f038c37d217de/data/redirs/fromDL_toFileServer.csv):

- https://github.com/digital-guard/preserv/blob/49c8f8065d9294e3aba1ffa5f50f038c37d217de/data/redirs/fromDL_toFileServer.csv#L370
- https://github.com/digital-guard/preserv/blob/49c8f8065d9294e3aba1ffa5f50f038c37d217de/data/redirs/fromDL_toFileServer.csv#L731

**Comment by 0e1** [comment]
Efetuei o download dos dois arquivos diretamente do armazenamento e comparei o sha256 dos dois arquivos.

Tratam-se do mesmo arquivo.

No commit https://github.com/digital-guard/preserv/commit/dcaa8cd31c12b2abb6942209a07a4a47a1e47745 mantive a linha adicionada mais recentemente.

**Comment by crebollobr** [comment]
Falta alguma coisa para fazer?

**Comment by 0e1** [comment]
> Falta alguma coisa para fazer?

Não, corrige e atualizei o banco de dados.

O que você pode fazer é **excluir** o arquivo https://addressforall-my.sharepoint.com/personal/operacao_addressforall_org/_layouts/15/download.aspx?share=EbBodLgdepJMijmBNw42bz4BJGKsQgx4NWBBdH-3arsXrQ da nuvem.

**Comment by 0e1** [comment]
Duplicação no csv resolvida, fechando a issue.
