### ISSUE TITLE
Readmes têm quebra de formatação

### ISSUE THREAD

**Issue by IgorEliezer** [digital-guard/preserv#151]
Era para ter uma quebra de linha/new line aqui:

![image](https://github.com/digital-guard/preserv-CO/assets/4673289/270bbb9f-883f-4127-9279-0e942cf19512)

Em:
* https://github.com/digital-guard/preserv-CO/tree/main/data/ANT/Medellin/_pk0002.01
* https://github.com/digital-guard/preserv-CO/tree/main/data/DC/Bogota/_pk0001.01
* https://github.com/digital-guard/preserv-CO/tree/main/data/VAC/Cali/_pk0007.01
* https://github.com/digital-guard/preserv-PE/tree/main/data/CUS/Cusco/_pk0001.01

Abri todos os readmes da América Latina e alguns por sorteio do BR. Não encontrei mais outros.

**Comment by 0e1** [comment]
Adicionei a quebra de linha e atualizei os readmes.

**Comment by IgorEliezer** [comment]
Confirmado.
