### ISSUE TITLE
Permitir a geração de link de download com sha.csv.gz

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv#167]
Na geração de grades temos arquivos csv gigantes e a ideia é colocar no drive e gerar links permanentes.
seria arquivo.csv gzip para arquivo.csv.gz
criar o sha256 dele e colocar no arquivo fromDL_toFileServer.csv

a ideia é extrair o arquivo.csv.gz e ele preservar o csv.

Exemplo 

GRADE-CM,CM-SW-Buea_logistic.csv.gz,CM,6f1839df4b1ad388a37b861edeaf1d678eb3aeb60704a2495052428444022e17.csv.gz,https://addressforall-my.sharepoint.com/personal/operacao_addressforall_org/_layouts/15/download.aspx?share=EQXmbO37GglFnOS1wuMJNW4ByALJAyNdqeI50s3tehD51Q

mas não permite realizar o make
```
carlos@addressforall:/var/gits/_dg/preserv/src$ make redirects_update pg_datalake=dl05s_main
mkdir -p /tmp/pg_io
-- Atualização de redirecionamentos --
--- dl.digital-guard.org ---
psql postgres://postgres@localhost/dl05s_main -c "SELECT download.insert_dldg_csv();"
ERROR:  new row for relation "redirects" violates check constraint "redirects_hashedfname_check"
DETAIL:  Failing row contains (GRADE-CM, CM-SW-Buea_logistic.csv.gz, CM, 6f1839df4b1ad388a37b861edeaf1d678eb3aeb60704a2495052428444022e17..., https://addressforall-my.sharepoint.com/personal/operacao_addres...).
CONTEXT:  SQL statement "INSERT INTO download.redirects(donor_id,filename_original,package_path,hashedfname,hashedfnameuri)
  SELECT donor_id,filename_original,package_path,de_sha256,para_url
  FROM tmp_orig.redirects_dlguard
  ON CONFLICT (hashedfname,hashedfnameuri)
  DO UPDATE
  SET donor_id=EXCLUDED.donor_id, filename_original=EXCLUDED.filename_original, package_path=EXCLUDED.package_path
  -- RETURNING 'Ok, updated download.redirects.'"
PL/pgSQL function download.insert_dldg_csv() line 3 at SQL statement
make: *** [makefile:206: redirects_update] Error 1
```

**Comment by 0e1** [comment]
Nginx atualizado e corrigido para permitir hash com múltiplas extensões.

`make redirects_update pg_datalake=dl05s_main` funcionando normalmente.
