### ISSUE TITLE
Criação automatica de apéndice para o Readme

### ISSUE THREAD

**Issue by ThierryAJean** [digital-guard/preserv#17]

**Comment by 0e1** [comment]
@ppKrauss lembrar de especificar essa issue.

**Comment by ppKrauss** [comment]
Na tabela `ingest.layer_file`, quando a ingestão é bem-sucedida um resumo é incluso como JSON, na coluna `feature_asis_summary`.  Gravar como YAML  em `results.yaml`  através de função PostgreSQL... Peter e Claiton estão preparando essa implementação. A partir do YAML será possível o usuári ooptar no make pelo target de geração de apêndice ao README. O texto poderia também ser mesclado às  evidências de teste.  

----

Outra sugestão é o README novo se chamar `README-test.md` de modo a ficar localmente para o usuário acrescentar por copia/cola a um antigo README as partes que faltam... Ver também [preserv/issues/10](https://github.com/digital-guard/preserv/issues/10) pois haverá impacto na opção de README.
