### ISSUE TITLE
Make join preserv-BR/data/RJ/Niteroi/_pk018

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv#18]
Para testar o make join fiz manualmente no ingest2 contando quantas linhas tem
select count(*) from pk18_002_p1_parcel join pk18_002_p4_cadparcel ON tx_insct = tx_insctec;
Registros no join acima 57605

registro no make all_joins
56250

Pode ser alguma coisa com tipo de dado?

**Comment by 0e1** [comment]
O processo de ingestão pode filtrar dados.

A função [ingest.join](https://github.com/AddressForAll/WS/blob/master/src/ingest-step1-ini.sql#L847), faz um update de _feature_asis_ a partir da tabela _cadastral_asis_.

Então comparar _join_ entre dados _não filtrados_ e _dados filtrados_ pode resultar em quantidades diferentes.

Assim, para avaliar tem que utilizar os dados filtrados disponíveis em _feature_asis_ e _cadastral_asis_.

**Comment by 0e1** [comment]
Meu entendimento é que  esse sql deve ser usado:


```
SELECT COUNT (*)
FROM
(    
    SELECT  *
    FROM ingest.feature_asis 
    WHERE file_id IN 
    (
        SELECT file_id 
        FROM ingest.layer_file 
        WHERE ftid IN 
            (
            SELECT ftid::int 
            FROM ingest.feature_type 
            WHERE ftname=lower('parcel_ext')
            ) 
            AND pck_fileref_sha256 = '4bde69d0057c0785598f98963fdae3dc90420fb8f163652d70b659210da0ae2b.zip'
    )
) AS asis

INNER JOIN

(
    SELECT  *
    FROM ingest.cadastral_asis 
    WHERE file_id IN 
        (
        SELECT file_id 
        FROM ingest.layer_file 
        WHERE ftid IN 
            (
            SELECT ftid::int 
            FROM ingest.feature_type 
            WHERE ftname=lower('cadparcel_cmpl')
            ) 
            AND pck_fileref_sha256 = '39d34950c7c61a89cfc2b4d70b0b34a85b346b41741331009205de0f06c86805.zip'
        )   
) AS cadis
    
ON asis.properties->'tx_insct' = cadis.properties->'tx_insctec'
```
Mas devagar com o andor.  A quantidade retornada pelo sql anterior será a quantidade de dados de _feature_asis_ que será atualizada pelo `make join-parcel`? Existe a possibilidade de não ser.

Ao executá-lo você obterá o seguinte:

```
 count 
-------
 57588
(1 row)
```

Sim, 57588 é diferente dos 55818 que são atualizados após o `make join-parcel` realizado. Por quê? Bem, a operação é feita com os dados que foram ingestados, incluindo os problemas que eles tiverem.

Ao agrupar pelos valores em ON `asis.properties->'tx_insct'` e `cadis.properties->'tx_insctec'` usando o sql:

```
SELECT COUNT (*)
FROM
(
    SELECT DISTINCT asis.properties->'tx_insct'
    FROM
    (    
        SELECT  *
        FROM ingest.feature_asis 
        WHERE file_id IN 
        (
            SELECT file_id 
            FROM ingest.layer_file 
            WHERE ftid IN 
                (
                SELECT ftid::int 
                FROM ingest.feature_type 
                WHERE ftname=lower('parcel_ext')
                ) 
                AND pck_fileref_sha256 = '4bde69d0057c0785598f98963fdae3dc90420fb8f163652d70b659210da0ae2b.zip'
        )
    ) AS asis

    INNER JOIN

    (
        SELECT  *
        FROM ingest.cadastral_asis 
        WHERE file_id IN 
            (
            SELECT file_id 
            FROM ingest.layer_file 
            WHERE ftid IN 
                (
                SELECT ftid::int 
                FROM ingest.feature_type 
                WHERE ftname=lower('cadparcel_cmpl')
                ) 
                AND pck_fileref_sha256 = '39d34950c7c61a89cfc2b4d70b0b34a85b346b41741331009205de0f06c86805.zip'
            )   
    ) AS cadis
        
    ON asis.properties->'tx_insct' = cadis.properties->'tx_insctec'

    GROUP BY cadis.properties->'tx_insctec', asis.properties->'tx_insct'
)
AS d
;
```

obtemos a quantidade distinta de linhas:

```
 count 
-------
 55706
(1 row)

```

Como 55706 é diferente de 57588, o resultado possui linhas repetidas. E fazer um update nesse situação gera, comportamento não previsível, conforme

_When a FROM clause is present, what essentially happens is that the target table is joined to the tables mentioned in the from_item list, and each output row of the join represents an update operation for the target table. When using FROM you should ensure that the join produces at most one output row for each row to be modified. In other words, a target row shouldn't join to more than one row from the other table(s). If it does, then only one of the join rows will be used to update the target row, but which one will be used is not readily predictable._ em [PostgreSQL: Documentation: 13: UPDATE](https://www.postgresql.org/docs/13/sql-update.html)

Referencio essa documentação porque a função por trás do `make join-parcel` é um `update` com clausula `from`.


Ah, 55706 também é diferente dos 55818 registros atualizados pela função ingest.join. Essa diferença de 112 eu não sei explicar, ainda. Mas deve estar relacionada a esse comportamento do `update` quando utilizado com `from`.



Em resumo, a diferença entre um update com clausula from e o `join realizado na mão` está relacionada às linhas repetidas produzidas, ou seja, aos problemas com os dados.

**Comment by ppKrauss** [comment]
Olá @0e1  e @crebollobr, a discussão gerou subsídios suficientes para criarmos um resumo na documentação (ou em um FAQ).

Meu parecer, por favor confirmem se resume corretamente:

1. As tabelas AsIs da Geometria e dos dados cadastrais estão sendo ingeridas 100%
2. A tabela AsIs cadastral pode ser utilizada para gerar listagens sumarizadas de nomes oficiais, etc. mas será descartada por sua redundância com a tabela da geometria, depois de feito o UPDATE.
3. 100% da Geometria é mantida no AsIs mas o UPDATE pode trazer menos de 100% dos dados cadastrais
4. Podemos definir um critério de "dados cadastrais bons" e "dados geométricos bons" para gerar o critério de **"percentual de UPDATEs mínimo"**. Se ocorrer JOIN-UPDATE com no mínimmo 80% das geometrias está aprovado, se menos o dado volta ou uma curadoria decide o que fazer. <br/>PS: menos de 80% pode ser indício de problemas com os identificadores ou "JOIN aleatório".

**Comment by 0e1** [comment]
#

> Olá @0e1 e @crebollobr, a discussão gerou subsídios suficientes para criarmos um resumo na documentação (ou em um FAQ).
> 
> Meu parecer, por favor confirmem se resume corretamente:
> 
>     1. As tabelas AsIs da Geometria e dos dados cadastrais estão sendo ingeridas 100%

Os dados cadastrais estão. Os geométricos **não** estão sendo ingeridos 100%, devido a [`geom IS NOT NULL AND ST_IsValid(geom)`](https://github.com/AddressForAll/WS/blob/master/src/ingest-step1-ini.sql#L695) em [any_load](https://github.com/AddressForAll/WS/blob/master/src/ingest-step1-ini.sql#L626).


>     2. A tabela AsIs cadastral pode ser utilizada para gerar listagens sumarizadas de nomes oficiais, etc. mas será descartada por sua redundância com a tabela da geometria, depois de feito o UPDATE.

Ok.


>     3. 100% da Geometria é mantida no AsIs mas o UPDATE pode trazer menos de 100% dos dados cadastrais

Sim. Majoritariamente pelos problemas com os identificadores que relacionam os dados.

>     4. Podemos definir um critério de "dados cadastrais bons" e "dados geométricos bons" para gerar o critério de **"percentual de UPDATEs mínimo"**. Se ocorrer JOIN-UPDATE com no mínimmo 80% das geometrias está aprovado, se menos o dado volta ou uma curadoria decide o que fazer. PS: menos de 80% pode ser indício de problemas com os identificadores ou "JOIN aleatório".

Concordo.



> Via email: mas ficou a dúvida de porque não usou DISTINCT... e se os dados duplicam com resultados diferentes, porque não excluir tais casos?  Apenas dados 100% devem ser agregados ao resultado, o resto será trabalho humano e investimento em horas humanas para decidir qual dado mais usar.

Concordo que mais casos devem ser excluídos do `UPDATE`. Eu não tinha me apercebido de como o `UPDATE` age em relação as linhas duplicadas presentes no join realizado quando `FROM` está presente. Então isso é uma coisa que precisa ser consertada. Ou seja, atender a isso: _When using FROM you should ensure that the join produces at most one output row for each row to be modified._

Para atender a isso, e a _apenas dados 100%_, qualquer identificador em _feature_asis_ que se relaciona com mais de um identificador em _cadastras_asis_ **não** deve ser atualizado.

Usar `DISTINCT` não resolve, primeiro que acho que não dá pra combinar com UPDATE. Segundo, porque de um grupo de linhas duplicadas ele retorna uma delas.


O esqueleto da função [ingest.join](https://github.com/AddressForAll/WS/blob/master/src/ingest-step1-ini.sql#L847) é:

```
UPDATE asis
SET asis.properties
FROM cad_asis
WHERE asis.x = cad_asis.y
```
Esse `UPDATE` funciona fazendo o join de `asis` com `cad_asis` e atualizando `asis`. Pra não ter o comportamento indesejado do `UPDATE`, o join de `asis X cad_asis` não deve ter linhas duplicadas.

Então, ao invés de usar a tabela cadastral_asis na clausula `FROM` do `UPDATE`, usar um join de `asis X cad_asis` removidas todas as linhas duplicadas.  O esquelto da função, ficaria algo como:

```
UPDATE asis
SET asis.properties
FROM join_asis_cadasis_clean
WHERE asis.x = join_asis_cadasis_clean.y
```

**Comment by ppKrauss** [comment]
@0e1  sobre o último comentário, fica a sugestão se consulta direta:
```sql
WITH checkDup AS (
  SELECT cad_id 
  FROM ingest.cadastral_asis
  WHERE file_id=123
  GROUP BY 1
  HAVING COUNT(*)>1
), join_asis_cadasis_clean AS (
  SELECT *
  FROM    ingest.cadastral_asis
  WHERE properties IS NOT NULL AND properties->>'xpto'>'' 
               AND  cad_id NOT IN (SELECT cad_id FROM checkDup)
)
 UPDATE ingest.feature_asis
 SET properties=j.properties
 FROM  join_asis_cadasis_clean j
 WHERE feature_asis.x = j.cad_id
```
PS: WITH é mais didático e elegante, mas pode perder performance. Na dúvida usar subqueries.
