### ISSUE TITLE
Licenças em novo atributo e make

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#19]
Cada  [*arquivo* de fonte primária](https://github.com/digital-guard/preserv/blob/main/docs/pt/list-primaryData-byJurisdic.md) de fonte primária precisa ter uma licença associada. Em geral uma mesma licença do doador é atribuida ao pacote (pk) inteiro.
 
As licenças possuem seus metadados e strings padronizadas conforme http://git.addressforall.org/licenses ([explícitas](http://git.addressforall.org/licenses/blob/master/data/licenses.csv) ou [implicitas](http://git.addressforall.org/licenses/blob/master/data/implieds.csv)), todas necessariamente vinculadas a uma [família](http://git.addressforall.org/licenses/blob/master/data/families.csv), conforme fixado pelo [Estatuto A4A, Figura-3](http://addressforall.org/_private/A4A-Estatuto2020-04-03.htm#Estatuto-anexo1).

Tarefas:

1. Incluir um interpretador para a tag `files_license`,  para o zip de licensa no `make_conf.yaml`.
2. Descrever no [Guia do make_conf](https://github.com/digital-guard/preserv/blob/main/docs/pt/man-makeConf.md) a metodologia.
3. Preparar os arquivos (zipar tudo junto) de 3 exemplos no git preserv-BR, com hash e PDF principal a ser digitalmente assinado por Igor, Thierry e Advogado.
4. gerar SHA256 e incluir no git 
5. Carlos fazer os demais

**Comment by ppKrauss** [comment]
@igor precisaremos de um conjunto completo de amostras de licença, umas 3 ou 4 "licenças boas", para desde já utilizarmos como exemplo de boa prática dos doadores,  e outras tantas "licença ruins", ilustrando situações onde ou a licença é juridicamente ruim (ambígua, não-padrão ou menos aberta), ou ausente (temos apenas confirmação da pessoa responsável) ou totalmente implícita (caso dos fornecedores federais que podem fazer isso).

**Comment by IgorEliezer** [comment]
> precisaremos de um conjunto completo de amostras de licença, umas 3 ou 4 "licenças boas",
@ppKrauss, há muitas cidades com licença domínio público. É só escolher umas que têm dados bons:
- AC-RioBranco
- CE-Fortaleza
- DF-Brasilia-dados.gov.br
- DF-Brasilia-GDF
- ES-Serra (descartar por ter cadastro incompleto)
- ES-VilaVelha
- ES-Vitoria
- MG-BeloHorizonte
- MG-Contagem
- MG-GovernadorValadares
- PR-Cascavel
- PR-Curitiba-Enio
- PR-SaoJosePinhais
-

**Comment by ppKrauss** [comment]
@IgorEliezer se a pasta OneDrive está organizada, então preciso apenas da listagem-bons (estou entendendo que passou acima) e da listagem-ruins (por favor passe aqui ~6 ruins).

**Comment by ppKrauss** [comment]
Resolver junto com https://github.com/digital-guard/preserv-BR/issues/27

**Comment by ppKrauss** [comment]
.. publicar por hora licencas em https://github.com/digital-guard/preserv/blob/main/docs/pt/list-primaryData-byJurisdic.md

**Comment by ppKrauss** [comment]
Retomando com @crebollobr  a geração padronizada dos dados de licença, fundamentamente arquivos `.eml` com o e-mail bruto da permissão de licença

**Comment by ppKrauss** [comment]
Ver também  https://github.com/digital-guard/licenses/issues/2

**Comment by crebollobr** [comment]
- [ ] AC-RioBranco
- [x] CE-Fortaleza
- [ ] DF-Brasilia-dados.gov.br ( precisa levantar essa fonte de dados )
- [ ] DF-Brasilia-GDF
- [ ] ES-VilaVelha
- [x] ES-Vitoria
- [x] MG-BeloHorizonte
- [x] MG-Contagem
- [ ] MG-GovernadorValadares
- [ ] PR-Cascavel
- [ ] PR-SaoJosePinhais
- [x] RS-PortoAlegre
- [ ] RS-SantaMaria
- [ ] SC-JaraguaSul (licença mista, contém dados do OSM)
- [ ] SC-Joinville
- [x] SP-Atibaia
- [ ] SP-Itu
- [ ] SP-LaranjalPaulista (material ruim, compõe-se de mapas no CAD)
- [ ] SP-SaoBernardoCampo
- [x] SP-SaoPaulo (a licença é por via decreto, similar à CC-BY ou CC-BY-SA)
- [ ] TO-Palmas

**Comment by crebollobr** [comment]
Migrado para https://github.com/digital-guard/preserv-BR/issues/27
