### ISSUE TITLE
Migrar run_mustache e procedimentos para PostgreSQL

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#22]
Devido à pobreza do  Mustache, que nem sequer faz [*anonymous list iteration*](https://github.com/bobthecow/mustache.php/issues/337), e que devido à complexidade do "pre-processamento inteligente" que gostaríamos de realizar no YAML, não resta outra alternativa senão realizar de forma mais elegante e interoperável esse pre-processamento: dentro do PostgreSQL.

O `makefile` faz a chamada pr `psql`, e usando funções de filesystem para indicar nomes de arquivo de entrada e de saída... Se for mais simples podemos criar uma função bash que pegue os argumentos sem precisar scape, etc.

-----

## Instalação

```sh
sudo apt install  postgresql-plpython3-13

# pegadinha no path de instalação do módulo, ver https://stackoverflow.com/a/69811157/287948
sudo su
cd ~
umask 022
sudo pip3 install  chevron
```

No SQL:
```sql
create extension plpython3u;
-- select * from pg_language;
CREATE or replace FUNCTION py3_return_version() RETURNS text AS $$
  import sys
  return sys.version
$$ LANGUAGE plpython3u;

CREATE FUNCTION lixo_chevron_test() RETURNS text AS $$
  import chevron
  return chevron.render('Hello, {{ mustache }}!', {'mustache': 'World'})
$$ LANGUAGE plpython3u;
select lixo_chevron_test();

CREATE or replace FUNCTION mustache_render(tpl text,i jsonb) RETURNS text AS $$
  import chevron
  import json
  
  j = json.loads(i)
  return chevron.render(tpl,j)
$$ LANGUAGE plpython3u IMMUTABLE;
-- select mustache_render('Hello, {{ mustache }}!', '{"mustache":"World"}'::jsonb);
```

**Comment by ppKrauss** [comment]
Conforme for desenvolvendo, criar exemplos e ASSERTs

**Comment by ppKrauss** [comment]
Parece que quase pronto,  fontes em uso e concluidas para a  solução desta *issue*:

- [ ] solução #24 com make rodando permissões depois de rodar o mustache.
- [ ] Funções ingest em https://github.com/digital-guard/preserv/blob/main/src/ingest-step1-ini.sql
- [ ] Funções em https://github.com/AddressForAll/pg_pubLib-v1/
- [ ] lógica "last" também em ingest-step1-ini.sql

**Comment by ppKrauss** [comment]
@0e1  podemos fechar? (se não houverem testes ou pendencias)

**Comment by 0e1** [comment]
Sim, podemos fechar.
