### ISSUE TITLE
Resolver definitivamente o problema das permissões

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#24]
Preparar makefile. Por exemplo para resolver permissões na pasta `$(gits)`, como *sudor* rodar make com algo 

```sh
chown -R postgres:www-data /opt/gits/
find  /opt/gits/* -type d -exec chmod 774 {} \+
find  /opt/gits/* -type f -exec chmod 664 {} \+
```

Idem  `/tmp/pg_io/`, etc.

-----

Outro problema é no final... Evidência de teste depois de chmod supostamente resolvido:

```
peter@server:/opt/gits/_dg/preserv-BR/data/MG/BeloHorizonte/_pk012$ make me
-- Updating this make --
python3 /opt/gits/_dg/preserv/src/run_mustache.py -b /opt/gits/_dg/ -t /opt/gits/_dg/preserv/src/maketemplates/make_ref027a.mustache.mk --tplLast=/opt/gits/_dg/preserv-BR/src/maketemplates/commomLast.mustache.mk -i ./make_conf.yaml --input0=/opt/gits/_dg/preserv-BR/src/maketemplates/commomFirst.yaml > /tmp/digitalPresservation-make_me.mk
/bin/sh: 1: cannot create /tmp/digitalPresservation-make_me.mk: Permission denied
make: *** [makefile:42: me] Error 2
```

**Apenas pastas controladas podem ser usadas**: a pasta `/tmp`  não é controlada, usar sandbox ou `/tmp/pg_io`.

**Comment by ppKrauss** [comment]
@crebollobr  e @0e1  por favor discutir aqui qual o código *chmod* correto para cada caso, que não pode ser 777, mas precisa ser o mais permissivo possível.

**Comment by 0e1** [comment]
dois problemas aqui:

1. permissões em `/opt/gits/`;
2. arquivos temporários durante a geração de `readme` e `makefile` em um `_pk*`.

Sobre 1: exceto o arquivo [gera_docs.bash](https://github.com/AddressForAll/documentation_generator/blob/main/gera_docs.bash), nenhum outro precisa de permissão de execução. Então, acho adequada a permissão `a+rw(664)`.

Sobre 2: detalhes adicionais (como um `ls -la` dos diretórios envolvidos) junto com a evidencia de teste, ajudariam a entender melhor o que aconteceu.
Na minha opinião, é  relacionado a concorrência e não diretamente à permissões, uma vez que assim que o arquivo temporário é criado, `chmod` é executado. O nome desses dois arquivos temporários é comum para todas as execuções de `make me`. Então pode acontecer de um usuário tentar criar um desses arquivos enquanto outro acabou de criá-lo sem ainda `chmod` ter sido executado [(commomLast.mustache.mk):](https://github.com/digital-guard/preserv-BR/blob/main/src/maketemplates/commomLast.mustache.mk#L46)

```
python3 $(srcPy) -b $(baseSrc)/ -t $(mkme_srcTpl) --tplLast=$(mkme_srcTplLast) -i $(mkme_input) --input0=$(mkme_input0) > $(mkme_output)
chmod 777 $(mkme_output)
```

Pode acontecer ainda, por exemplo, de um `makefile` referente a um `pkid` ser copiado para outro `pkid`. Esse segundo, é um problema mais grave, no meu entender.

Então, associar o nome desses arquivos temporários ao `pkid` evita esses problemas. Não evitando a situação onde dois usuários resolvam executar `make me` em um mesmo `pkid`, mas essa acho uma situação rara e que não precisaria ser tratada.

Associando o `pkid` ao nome dos arquivos temporários, as permissões desses arquivo pode ser `744`. Assim, se dois usuários executarem `make me`, no mesmo instante, em um mesmo `pkid`, vai dar erro.

**Comment by ppKrauss** [comment]
Resolvido com um script bash reusado por todos os targets, e sendo chamado com sudo, 
```mk
target: etc
	@echo "... Fixando permissões padronizadas:"
	sudo fixaPermissoes.sh /tmp/pg_io /opt/gits
```
