### ISSUE TITLE
migrar de WS para cá os scripts de redirects

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#25]
o SQL Schema Optim é para a otimização e consolidação de endereços do AddressForAll. A função e tabela *redirects* é de uso exclusivo dos downloads no subdomínio DL do domínio *Digital-Guard.org*, portanto sugere-se adotar o SQL **Schema Download** (a sigla DL já foi antes reservada para Data Lake) no lugar de Optim.
 
https://github.com/AddressForAll/WS/blob/master/src/optim-step1-ini.sql#L366

**Comment by 0e1** [comment]
Realizei a migração. Avaliar os commits: 
https://github.com/AddressForAll/WS/commit/657b90c7546a7388246e5b4d5a0a81dd65648c2b
https://github.com/digital-guard/preserv/commit/07b428f26376c90e8d480d44187b5b4a6ee938d2

**Comment by 0e1** [comment]
Outras issues relacionadas:
https://github.com/digital-guard/preserv/issues/28
https://github.com/AddressForAll/WS/issues/28

Migração concluída e em funcionamento.
