### ISSUE TITLE
Incluir mais funções de preparo do input para a renderização

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#3]
No bloco de "Preparo do input para renderização", em  https://github.com/cchness/preserv/blob/dev/src/run_mustache.py#L144
precisarmos  incluir mais funções de transformação de estrutura, em particular os flags hoje resulvidos por *bash* mas que poderiam já ser resolvidos pelo Mustache. 

----
Exemplo de [código makefile **indesejado**](https://github.com/AddressForAll/digital-preservation-CO/blob/main/data/in/IGAC/_pk003/make_conf.yaml) que poderia ser resolvido pelo Mustache:
```
ifeq ('shp2sql','shp2sql')
	@echo Executando shp2pgsql ...
	cd $(sandbox);	shp2pgsql   -s 4686 "shp/U_NOMENCLATURA_DOMICILIARIA.shp" $(tabname) | psql -q $(pg_uri_db) 2> /dev/null
endif
ifeq ('shp2sql','csv2sql')
	@echo Executando csc2sql ...
	psql $(pg_uri_db) -c "SELECT ingest.fdw_generate_direct_csv( '$(sandbox)/shp/U_NOMENCLATURA_DOMICILIARIA.csv', '$(tabname)' )"
endif
	psql $(pg_uri_db) -c "SELECT ingest.any_load('shp2sql','$(sandbox)/shp/U_NOMENCLATURA_DOMICILIARIA','$(layername)','$(tabname)','$(fullPkID)','$(part1_file)',array['gid', 'texto AS house_number', 'geom'])"
	@echo "Confira os resultados nas tabelas ingest.layer_file e ingest.feature_asis".
ifeq ('shp2sql','csv2sql')
	psql $(pg_uri_db) -c "DROP FOREIGN TABLE IF EXISTS $(tabname)"
endif
```

**Comment by cchness** [comment]
Para que Mustache trata as condicionais são necessárias também as modificações em: https://github.com/digital-guard/preserv-BR/pull/2
