### ISSUE TITLE
Versão de ingest migrada diferente da original

### ISSUE THREAD

**Issue by 0e1** [digital-guard/preserv#34]
A migração de ingest de WS para preserv suprimiu linhas de código, foram de 961 para 797. A diferença pode ser maior ainda, considerando que a versão migrada já sofreu acréscimos.

Último commit em WS: https://github.com/AddressForAll/WS/commit/0c02e9a08ca16c8ecc6909dc113bc93d624218d0
Primeiro commit em preserv: https://github.com/digital-guard/preserv/commit/7d35d9d6df160095548b3cad95d73d4ad23e518e#diff-8cff83abecbc68d061ba8cd52af7269f9df92d236256a520e3fdce6a457da1fe

**Comment by ppKrauss** [comment]
Sim, precisaremos testar os makefiles novamente. Como são muitos podemos adotar critério de amostragem. Por favor @0e1, depois de atualizar os projetos *git* *preserv*, *preserv-BR* e *preserv-CO* com o novo makefile, indicar  quais pk's já foram testados com geração `make me` e quais tiveram também o `make all` homologado.

**Comment by 0e1** [comment]
Avaliei todos os diretórios em preserv-BR/data. Recuperei as linhas de códigos necessárias para o funcionamento.
Na lista a seguir, os pkid sem nenhum comentário estão funcionando, com make all_layers executando sem erros. Lista referente a jurisdição BR, por hora.

- 46
- 24
- 23 sem make_conf.yaml
- 12
- 37
- 21
- 48 sem make_conf.yaml
- 16
- 30 sem make_conf.yaml
- 41
- 29
- 42 sem make_conf.yaml
- 18
- 68 sem make_conf.yaml
- 14
- 69 sem make_conf.yaml
- 86
- 27
- 70 sem make_conf.yaml
- 31 funcionando após ajustar make_conf.yaml com a alteração https://github.com/digital-guard/preserv-BR/commit/bf953993f7b5dc45ec5b42e78c06825b3d7a0645#diff-30102fbab137d49fec96d9c742b19c06a7fddafc293f5becc1b58141421edd8d
- 59
- 44 sem make_conf.yaml
- 39
- 55 sem make_conf.yaml
- 71 sem make_conf.yaml
- 52 sem make_conf.yaml
- 10 sem make_conf.yaml
- 28 sem make_conf.yaml
- 32 sem make_conf.yaml
- 15 sem make_conf.yaml
- 26 sem make_conf.yaml
- 45
- 58
- 20
- 47 sem make_conf.yaml
- 35
- 13 sem make_conf.yaml
- 17
- 75
- 
- 2 lixo
- 60 id_log nao existe, issue https://github.com/digital-guard/preserv-BR/issues/51
- 67  issue https://github.com/digital-guard/preserv-BR/issues/52
- 38 issue https://github.com/digital-guard/preserv-BR/issues/52

**Comment by 0e1** [comment]
Ainda hoje testo os makefile das demais jurisdições.

Para inicializar a base e rodar make me:

```

create database ingest1;
CREATE EXTENSION IF NOT EXISTS hstore;
CREATE EXTENSION IF NOT EXISTS postgis;

Em /var/gits/_dg/WS/src rodar
make ini_tmprefresh

psql postgres://postgres@localhost/ingest1 < /var/gits/_a4a/WS/src/pubLib.sql
psql postgres://postgres@localhost/ingest1 < /var/gits/_a4a/WS/src/sys_pubLib.sql

psql postgres://postgres@localhost/ingest1 < /var/gits/_a4a/pg_pubLib-v1/src/pubLib01-array.sql
psql postgres://postgres@localhost/ingest1 < /var/gits/_a4a/pg_pubLib-v1/src/pubLib01py-string.sql
psql postgres://postgres@localhost/ingest1 < /var/gits/_a4a/pg_pubLib-v1/src/pubLib03-admin.sql
psql postgres://postgres@localhost/ingest1 < /var/gits/_a4a/pg_pubLib-v1/src/pubLib03-json.sql
psql postgres://postgres@localhost/ingest1 < /var/gits/_a4a/pg_pubLib-v1/src/pubLib05hcode-distrib.sql

psql postgres://postgres@localhost/ingest1 < /var/gits/adg/preserv/src/ingest-step1-ini.sql


SELECT ingest.lix_insert('BR','/var/gits/_dg/preserv-BR/src/maketemplates/commomFirst.yaml','first_yaml');
SELECT ingest.lix_insert('BR','/var/gits/_dg/preserv-BR/src/maketemplates/readme.mustache','readme');

SELECT ingest.lix_insert('PE','/var/gits/_dg/preserv-PE/src/maketemplates/commomFirst.yaml','first_yaml');
SELECT ingest.lix_insert('PE','/var/gits/_dg/preserv-PE/src/maketemplates/readme.mustache','readme');

SELECT ingest.lix_insert('PE','/var/gits/_dg/preserv-CO/src/maketemplates/commomFirst.yaml','first_yaml');
SELECT ingest.lix_insert('PE','/var/gits/_dg/preserv-CO/src/maketemplates/readme.mustache','readme');

SELECT ingest.lix_insert('INT','/var/gits/_dg/preserv/src/maketemplates/make_ref004a.mustache.mk','mkme_srcTpl');
SELECT ingest.lix_insert('INT','/var/gits/_dg/preserv/src/maketemplates/make_ref027a.mustache.mk','mkme_srcTpl');
SELECT ingest.lix_insert('INT','/var/gits/_dg/preserv/src/maketemplates/commomLast.mustache.mk','mkme_srcTplLast');


Em /var/gits/preserv-BR/src rodar
make all

E na pasta do pacote de dados make me e make all_layers
```

**Comment by 0e1** [comment]
Testei as jurisdições CO e PE. Após remoções de zeros à esquerda nos pkid dos make_conf.yaml, todos estão com a ingestão, por meio do make all_layers, funcionando.

**Comment by ppKrauss** [comment]
Quando base `ingest1`  não existe precisa criar, ou indicar como criar (como target no make ou ex, delegando para o preserv).

**Comment by ppKrauss** [comment]
@0e1  Ok, fiz uma pequena atualização mas ainda faltam varios detalhes para rodar make do zero, ver https://github.com/digital-guard/preserv/commit/1f69b45a7d0edb4440c70ce01772f29e02635f33

**Comment by 0e1** [comment]
Os códigos perdidos durante a migração, já foram recuperados. A abordagem adotada para recuperar foi: apareceu um problema, recupera o código na última versão em https://github.com/AddressForAll/WS/commit/0c02e9a08ca16c8ecc6909dc113bc93d624218d0, e o adiciona/substitui onde for necessário. E, passado um tempo em aparecer problemas, considero que essa issue pode ser fechada.
