### ISSUE TITLE
Dividir responsabilidades entre WS e Preserv

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#37]
O Projeto Preserv deve ser independente, rodar como *standalone*, e antes do [AddressForAll/WS](http://git.AddressForAll.org/WS).
Todavia há um legado, tal como o uso da tabela `optim.jurisdiction` ou das tabelas definidoras de tipo no schema API da  eclusa.

Precisamos decidir qual projeto fica responsável por qual parte, decidir se rodam em *databases*  diferentes (se diferirem estabelecer convencções de nome), e se rodam as consultas como [postgres-fdw](https://www.postgresql.org/docs/current/postgres-fdw.html), etc.

-----------

Dump do bug atual no `make all_ini`:

```
ERROR:  schema "api" does not exist
ERROR:  relation "optim.origin" does not exist
LINE 9:   INSERT INTO optim.origin(jurisd_osm_id,pack_id,fhash, fnam...
                      ^
ERROR:  relation "eclusa.vw01_cityfolder_validusers" does not exist
LINE 3:   FROM eclusa.vw01_cityfolder_validUsers
               ^
CREATE FUNCTION
CREATE FUNCTION
ERROR:  relation "optim.origin" does not exist
LINE 16:     FROM optim.origin WHERE is_open AND is_valid
                  ^
ERROR:  schema "api" does not exist
ERROR:  function eclusa.cityfolder_validusers() does not exist
LINE 2:   SELECT name as username FROM eclusa.cityfolder_validUsers(...
                                       ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
ERROR:  function eclusa.cityfolder_input_files(text) does not exist
LINE 21:      FROM eclusa.cityfolder_input_files(p_user) -- não mais ...
```

**Comment by ppKrauss** [comment]
@0e1  o que acha, resolvido, podemos fechar?

**Comment by 0e1** [comment]
Sim, não existe mais dependência com WS.
