### ISSUE TITLE
make insert_size e demais preparatórios

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#44]
PS: para reproduzir todo processo no ingest99 usei [wiki/Testes-com-ingest99](https://github.com/digital-guard/preserv/wiki/Testes-com-ingest99) (favor editar/atualizar com o que mais for necessário)... fiz `nano   /var/gits/_dg/preserv-BR/src/maketemplates/commomFirst.yaml` para  testar tudo na ingest99 (ao invés de ingest1).

## make me

Apesar de eu ter modificado o  `commomFirst` para *ingest99*, o makefile gerado continua com *ingest1*.
 
## make insert_size
Precisa preservar o YAML original, com sua mesma ordem e comentários, senão o `git diff` não vai destacar a mudança, e haverá risco também de bugs passarem desapercebidos.  Os comentários também não deveriam ser  eliminados. Algoritmo de publicação final no caso de `make insert_size`:

1. Resgatar o YAML original como text
2. Substituir o bloco `files`  inteiro por `{{files}}`  ou placeholder com mesmo significado
3. ingetar no YAML o JSON de `files` (que agora tem size)  convertido para YAML. Apenas isso.

## make delete_file
Ainda está baseado em *ingest.layer_file*, atualizar

## make readme
```
psql postgres://postgres@localhost/ingest99 -c "SELECT ingest.lix_generate_readme('BR','42.1');"
ERROR:  TypeError: the JSON object must be str, bytes or bytearray, not NoneType
CONTEXT:  Traceback (most recent call last):
  PL/Python function "jsonb_mustache_render", line 4, in <module>
    j = json.loads(i)
  PL/Python function "jsonb_mustache_render", line 340, in loads
PL/Python function "jsonb_mustache_render"
SQL statement "SELECT jsonb_mustache_render(readme, conf_yaml)"
PL/pgSQL function ingest.lix_generate_readme(text,text) line 15 at SQL statement
make: *** [makefile:51: readme] Error 1
```

## make insert_make_conf.yaml
1. Mudar o nome para insert_make_conf já que não existe outro na pasta.
2. Explicar no Guia e indicar no `make info` o objetivo de fazer isso: preciso ou não preciso fazer isso para efetuar a ingestão?

**Comment by 0e1** [comment]
#

> ## make me
> 
> Apesar de eu ter modificado o `commomFirst` para _ingest99_, o makefile gerado continua com _ingest1_.

[`make ini_all`](https://github.com/digital-guard/preserv/blob/main/src/makefile#L95) carrega `commonFirst` (de cada jurisdição. Lembrar que o preserv puro também faz ingestão de dados, tendo também um arquivo commomFirst) na base de dados por meio de [ingest-step2-ini-make.sql](https://github.com/digital-guard/preserv/blob/main/src/ingest-step2-ini-make.sql)

Alterações posteriores em `commonFirst` necessitam um novo carregamento do arquivo. Por enquanto isso deve ser feito manualmente. É necessário um target para isso?

**Comment by 0e1** [comment]
> ## make delete_file
> 
> Ainda está baseado em _ingest.layer_file_, atualizar

A tabela [ingest.layer_file](https://github.com/digital-guard/preserv/blob/main/src/ingest-step1-ini.sql#L235) tinha `pck_fileref_sha256` que era utilizado pelo target para deletar .

A tabela [ ingest.donated_PackComponent](https://github.com/digital-guard/preserv/blob/main/src/ingest-step1-ini.sql#L213) não contem mais essa coluna. Então, será utilizado o `id` para realizar o delete.

**Comment by 0e1** [comment]
> ## make insert_make_conf.yaml
> 
>     1. Mudar o nome para insert_make_conf já que não existe outro na pasta.
> 
>     2. Explicar no Guia e indicar no `make info` o objetivo de fazer isso: preciso ou não preciso fazer isso para efetuar a ingestão?

Nome alterado.
Ao executar `make me`, o target `insert_make_conf`é executado. Então, não precisa executá-lo antes. Além disso, todos os targets atuais que utilizam o `make_conf.yaml` estão executando o target `insert_make_conf`.

**Comment by 0e1** [comment]
> ## make readme
> 
> ```
> psql postgres://postgres@localhost/ingest99 -c "SELECT ingest.lix_generate_readme('BR','42.1');"
> ERROR:  TypeError: the JSON object must be str, bytes or bytearray, not NoneType
> CONTEXT:  Traceback (most recent call last):
>   PL/Python function "jsonb_mustache_render", line 4, in <module>
>     j = json.loads(i)
>   PL/Python function "jsonb_mustache_render", line 340, in loads
> PL/Python function "jsonb_mustache_render"
> SQL statement "SELECT jsonb_mustache_render(readme, conf_yaml)"
> PL/pgSQL function ingest.lix_generate_readme(text,text) line 15 at SQL statement
> make: *** [makefile:51: readme] Error 1
> ```
> 
> ##

Retestar. Provavelmente relacionado ao usar ingest1, pela falta de atualizar no banco de dados o commomFirst. Com a versão correta aparentemente está funcionando.

**Comment by ppKrauss** [comment]
`regexp_replace( pg_read_file('/tmp/pg_io/lix.yaml') ,  '\nfiles: *(\n(?:\-|\s+)[^\n]*)+', E'\n{{files}}', 'n')`

**Comment by 0e1** [comment]
> regexp_replace( pg_read_file('/tmp/pg_io/lix2.yaml') , '\nfiles: *(\n *\-[^\n]*|\n[\t ]+[^\n]+)+', E'\n{{files}}', 'n');

O resultado:

```
make insert_size 
-- Carrega make_conf.yaml na base de dados. --
Uso: make insert_make_conf
pack_id: 19.1
[ENTER para continuar ou ^C para sair]

psql postgres://postgres@localhost/ingest99 -c "SELECT ingest.lix_insert('/var/gits/_dg/preserv-BR/data/RS/SantaMaria/_pk0019.01/make_conf.yaml');"
NOTICE:  ext orig_filename_ext : make_conf.yaml
NOTICE:  ext orig_filename_ext : BR
 lix_insert 
------------
 
(1 row)

-- Updating make_conf with files size --
psql postgres://postgres@localhost/ingest99 -c "SELECT ingest.lix_generate_make_conf_with_size('BR','19.1');"
 lix_generate_make_conf_with_size 
----------------------------------
 Ok. Content bytes writed:1550   +
 See /tmp/pg_io/make_conf_BR19.1
(1 row)

sudo chmod 777 /tmp/pg_io/make_conf_BR19.1
 Check diff, the '<' lines are the new ones... Something changed?
7,18d6
< - file: 51a6beb9fca43e0fb45727138982f7806b8df52fce53f5e0e31edd61bfbc21b9.rar
<   name: Lotes
<   p: 1
<   size: '4656161'
< - file: f4d3819f9853e85e43bf7a58de7f257eed5f63bcf36daed1c4db0f2701544adc.zip
<   name: Eixos
<   p: 2
<   size: '2053392'
< - file: 9600dcba403c8dc0b066c8f429507e4672966a01c93119923f75361a6ebc64c0.zip
<   name: Bairros
<   p: 3
<   size: '5204795'
19a8,20
> files:
>   -
>     p:    1
>     file: 51a6beb9fca43e0fb45727138982f7806b8df52fce53f5e0e31edd61bfbc21b9.rar
>     name: Lotes
>   -
>     p:    2
>     file: f4d3819f9853e85e43bf7a58de7f257eed5f63bcf36daed1c4db0f2701544adc.zip
>     name: Eixos
>   -
>     p:    3
>     file: 9600dcba403c8dc0b066c8f429507e4672966a01c93119923f75361a6ebc64c0.zip
>     name: Bairros
If some changes, and no error in the changes, move the script:
 mv /tmp/pg_io/make_conf_BR19.1 ./make_conf.yaml
[ENTER para rodar mv ou ^C para sair]
```

**Comment by ppKrauss** [comment]
> O resultado:

Entendo que foi resolvido, certo?   (importante sempre indicar as suas conclusões quando postar alguma *evidência de teste*)

Se foi resolvido, um bug secundário:  porque está gerando strings? por exemplo ` '4656161'`  ao invés de  `4656161`?

**Comment by 0e1** [comment]
Corrigi, agora retorna um número: https://github.com/digital-guard/preserv/commit/66d0e79c4343eaa974b07677bf5df3f4fa96e250.

Considero resolvido.

**Comment by 0e1** [comment]
Aparentemente, tudo resolvido. Fechando issue.
