### ISSUE TITLE
Interface para navegar nos dados filtrados

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#46]
Com base neste primeiro rascunho,  http://osm.codes/mapTest1.htm   , fazer as seguintes melhoras:

- [ ] Ajustar onMouseOver para não deixar rastros
- [ ] Mostrar ícones menores no primeiro zoom dos pontos
- [ ] Mostrar icones normais e trocar imagem de fundo para satélite MapBox (ou algo que não apague) quando zoom maior.
- [ ] Seletor externo de geohashes para saltar direto sem uso do mapa
- [ ] Detector de URL para já abrir nos pontos desejados 
- [ ] ...

**Comment by elpbatista** [comment]
Encontré este proyecto que parece interesante https://react-leaflet.js.org`

**Comment by ppKrauss** [comment]
> Encontré este proyecto que parece interesante https://react-leaflet.js.org

Bom achado, parece que [tem equipe ativa em manutenção](https://github.com/PaulLeCam/react-leaflet/graphs/contributors?from=2020-11-16&to=2022-01-12&type=c)... Vamos então em frente:

1. Decidir se essa página precisa React ou se basta "Leaflet puro".
2. Implementar a issue e levar para a produção, em digital-guard.org, a primeira versão desta página.
3. Acrescentar mais dados e navegabilidade na página, conforme [list-primaryData-byHash](https://github.com/digital-guard/preserv/blob/main/docs/pt/list-primaryData-byHash.md).
3. Em um futuro próximo (~fevereiro) decidir quais serão os frameworks dos sites da AddressForAll... Já decidimos que no desenvolvimento e [documentação](http://docs.addressforall.org/) utilizaremos [Vega-lite](https://vega.github.io/vega-lite/), mas as interfaces finais podem exigir algo mais sofisticado, como [AntV](https://dev.to/antdesignui/introduce-antv-a-new-player-in-data-visualization-3jf5) (ex.  [I7 district/basic/province](https://l7.antv.vision/en/examples/district/basic#province)) ou [react-geo](https://terrestris.github.io/react-geo/docs/latest/index.html#!/Components/Grids/AgFeatureGrid/AgFeatureGrid/1) (plugin over AntV), etc. e em seguida a decisão entre OpenLayers (parece que react-geo e AntV/L7 usam) e Leaflet.

**Comment by elpbatista** [comment]
1. Según los requerimientos iniciales:
  Para interacción básica como zoom, select, icons, click, pop-up; se puede resolver desde Leaflet. 
  NO es necesario usar React para:
  - Ajustar onMouseOver para não deixar rastros
  - Mostrar ícones menores no primeiro zoom dos pontos
  - Mostrar icones normais e trocar imagem de fundo para satélite MapBox (ou algo que não apague) quando zoom maior.
  Para tablas y formularios que no son componentes del mapa es necesario incluir una library:
  Es necesario usar React (o cualquier otro JS framework) para:
 - Seletor externo de geohashes para saltar direto sem uso do mapa
Puede resolverse con JavaScript puro:
 - Detector de URL para já abrir nos pontos desejados
 En ambos casos se puede incluir estilos en un file *.css de la manera tradicional https://reactjs.org/docs/faq-styling.html

**Comment by elpbatista** [comment]
map full screen + floating table  VS horizontal split = half table + half map
![map_full](https://user-images.githubusercontent.com/5332055/149254611-3c9dca1f-07b8-4afe-ac6c-24d82591e814.png)
![map_half](https://user-images.githubusercontent.com/5332055/149254633-b453dd85-4602-4bf8-b010-821004032b64.png)

**Comment by ppKrauss** [comment]
> NO es necesario usar React para: ...

Ok, vamos fazer algo simples e rápido com isso. Para tabelas e outras formas de reatividade usamos URL

> Detector de URL para já abrir nos pontos desejados

ok.

> map full screen + floating modal VS horizontal split = half table + half map

por hora não usaremos "map full screen", será uma página com [template estático](https://en.wikipedia.org/wiki/Web_template_system#Static_site_generators) e o mapa no meio, como no rascunho (`mapTest1.htm `).

Em paralelo montaremos juntos o projeto de todas  as interfaces, e aí sim iniciaremos com React: estamos adiantando, ao invés de esperar já "saltaremos" para todo o site em React... Por isso  mapTest1 é só um teste para demonstrar recursos e ajudar as pessoas não-tecnicas a tomarem decisões.
