### ISSUE TITLE
criar target especializado em pg_dbingest

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#49]
Atualmente  o [make do preserv](https://github.com/digital-guard/preserv/blob/main/src/makefile) só oferece o target `ini_all`  que cria (e destroi!) ambas as bases, `pg_db` e `pg_dbingest`.  No dia-a-dia precisamos rodar apenas com `pg_dbingest` para testar ou processas na produção as ingestões.

**Comment by 0e1** [comment]
Melhorei https://github.com/digital-guard/preserv/wiki/Testes-com-ingest99. Ver se está mais claro como criar uma ingest[0-9]{1,} qualquer e que `pg_db` é apenas criado por `ini_all` mas inicializado por outro target.
