### ISSUE TITLE
Funções de formatação de ID e seu uso 

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#51]
Os novoes IDs de donor, donatedPack, etc. requerem formatação. A versão formatada é utilizada por exemplo na nomenclatura de tabelas relativas aos pacotes, por exemplo
```
 public | pk17000000101401_p4_geoaddress         | table    | postgres
 public | pk7600002901101_p1_geoaddress          | table    | postgres
 public | pk7600003001101_p1_geoaddress          | table    | postgres
```

Reparar que foi usado o bigint de packVersion mas mesmo o bigint precisa ser formatado, para ficarem com o mesmo número de dígitos, Brasil (76) e Colombia (170) precisam ter mesmo número de dígitos. Falta o  `lpad('7600002901101', 14, '0')` para obter:

```
pk17000000101401_p4_geoaddress 
pk07600002901101_p1_geoaddress4
```
## Lib dos casts e formatadores
.... funções padronizadas como antes

## Guia de como e quando formatar

* formatar ID inteiro como inteiro: basta o `lpad`
* formatar ID inteiro como string com pontos:  *package 170.000001.01.4.01*  (?)
* ...

**Comment by 0e1** [comment]
Tarefas listadas em #69.
