### ISSUE TITLE
GeoJSON no está bien formado

### ISSUE THREAD

**Issue by elpbatista** [digital-guard/preserv#52]
https://raw.githubusercontent.com/digital-guard/preservCutGeo-BR2021/main/data/MG/BeloHorizonte/_pk0008.01/geoaddress/geohahes.geojson

Falta el objeto "geometry" como se especifica en https://geojson.org. Aunque algunos intérpretes (parsers) lo entienden y es un JSON válido, no cumple con la especificación del GeoJSON rfc7946.
En mi caso he perdido tiempo intentando encontrar el error (undifined al invocar feature.geometry.type) porque se espera que "type" y "coordinates" sean propiedades del objeto "geometry" y no que fueran propiedades directas de "feature"

Otra cosa que no es un error pero se debería solucionar es que los valores de las "properties": "val", "lghs" y "val_density_km2" son actualmente cadenas y deberían ser números

"properties": {"ghs": "7h2", "val": "405", "lghs": "3", "val_density_km2": "50.177524849127586"}
por
"properties": {"ghs": "7h2", "val": 405, "lghs": 3, "val_density_km2": 50.177524849127586},

Las features deberían ser del tipo "Polygon" si la geometría corresponde a una sola figura cerrada (empieza y termina con el mismo par de coordenadas) ¿Es realmente necesario que sean "type": "MultiPolygon"?

**Comment by ppKrauss** [comment]
* Sobre RFC 7946, exemplos da [sec 3.1.9](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.9) e a maioria dos softwares   não usam `geometry` (é **redundante**), enquanto [exemplo da sec 1.5](https://datatracker.ietf.org/doc/html/rfc7946#section-1.5)  usa. Precisamos avaliar melhor as boas práticas mais difundidas na comunidade Geo.

* Sobre tipo *string* em `val` e demais itens de `properties`, que deveriam ser tipo *number*: concordo, é um bug, vamos corrigir.

* Sobre uso mesclado MultiPolygon/Polygon: sim, é necessário, repare no caso do conjunto de células do Geohash `7h2` , são 4 polígonos disjuntos e distantes entre si; enquanto `7h2z1` é de fato *Polygon*.

**Comment by elpbatista** [comment]
El objeto Feature descrito  en [sec 3.2](https://datatracker.ietf.org/doc/html/rfc7946#section-3.2) tiene 3 members, los tres son mandatories. La sec 3.1.9 está describiendo prescisamente una extensión del objeto Geometry o MultyGeometry. 
Los softwares lo que hacen es reformatear el GeoJson y tratar de levarlo al formato correcto. En esta caso Leaflet (ver imagen adjunta) crea su propio objeto geometry correpondiente al type que recibe y crea además el nivel superior con "type"="Feature" que necesita, agregando además un objeto "properties" vacío en la posición que le correspondería a las propiedades según el standard (ver columna derecha de la imagen adjunta) Eso hace que las properties que vienen con los datos queden en un nivel más adentro y para acceder a ellas en lugar de:

"features[n].properties" sea necesario "features[n].geometry.properties" así que la malformación de los datos está introduciendo un error. 

De todas formas he conseguido hacer que funcione pero sigue sin ser el comportamiento esperado. A mi modo de ver es más un error que una práctica aceptable.

![Screen Shot 2022-01-18 at 3 43 56 PM](https://user-images.githubusercontent.com/5332055/150038369-15a73ed2-4fd7-4e1a-aa87-1e42bef1020f.png)

**Comment by ppKrauss** [comment]
> El objeto Feature descrito en [sec 3.2](https://datatracker.ietf.org/doc/html/rfc7946#section-3.2) tiene 3 members, los tres son mandatories. La sec 3.1.9 está describiendo prescisamente una extensión del objeto Geometry o MultyGeometry. (...)
> Los softwares lo que hacen es reformatear el GeoJson y tratar de levarlo al formato correcto.

Ok, faz sentido.  Vamos então arrumar... Acredito que o problema esteja [nesta função ST_AsGeoJSONb](https://github.com/AddressForAll/pg_pubLib-v1/blob/main/src/pubLib06pgis-geoJSON.sql#L60). 

PS: bug da string corrigido, ver *raw file* [geohahes.geojson](https://raw.githubusercontent.com/digital-guard/preservCutGeo-BR2021/main/data/MG/BeloHorizonte/_pk0008.01/geoaddress/geohahes.geojson)

**Comment by 0e1** [comment]
> Ok, faz sentido. Vamos então arrumar... Acredito que o problema esteja [nesta função ST_AsGeoJSONb](https://github.com/AddressForAll/pg_pubLib-v1/blob/main/src/pubLib06pgis-geoJSON.sql#L60).

Ajuste em https://github.com/AddressForAll/pg_pubLib-v1/commit/c39768c2a9ab03208a0bd127d9d61abf677ecbe6.

**Comment by 0e1** [comment]
https://github.com/AddressForAll/pg_pubLib-v1/commit/c39768c2a9ab03208a0bd127d9d61abf677ecbe6 introduz uma nova lina, removida na regex https://github.com/AddressForAll/pg_pubLib-v1/blob/main/src/pubLib03-json.sql#L170.

Ver exemplo do resultado final, em conjunto com #53: https://raw.githubusercontent.com/digital-guard/preservCutGeo-BR2021/main/data/MG/BeloHorizonte/_pk0008.01/geoaddress/pts_7h2wme.geojson

**Comment by 0e1** [comment]
Foi implementado opção para gerar mosaico sem espaços e quebras de linha. Ver [publicação](https://github.com/digital-guard/preserv/wiki/Testes-com-ingest99#publica%C3%A7%C3%A3o).

A opção `pretty_opt=3` faz a função [jsonb_pretty_lines](https://github.com/AddressForAll/pg_pubLib-v1/blob/main/src/pubLib03-json.sql#L166) remover espaços e quebras de linha (Até então, os mosaicos eram gerados com pretty_opt=2). Essa opção não afeta a geração dos arquivos _pts*_.

Exemplo de mosaico geojson gerado com essa opção: [_pk0004.01/geoaddress/geohahes.geojson](https://raw.githubusercontent.com/digital-guard/preservCutGeo-BR2021/main/data/_pk0004.01/geoaddress/geohahes.geojson).

**Comment by ppKrauss** [comment]
@elpbatista resolvido?

**Comment by ppKrauss** [comment]
Qualquer problema retomar em https://github.com/digital-guard/preservDataViz/issues/2 ou nova issue por lá.
