### ISSUE TITLE
revisar correcao do write_geoJSONb_Features ou precursor

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#53]
A nova modificação acarretou mudanças inesperadas (bugs), se possível corrigir.

## alteração da ordem 
![image](https://user-images.githubusercontent.com/1651447/150044586-e0c6bafd-13e2-430a-8865-adb8bf1bd77b.png)

## inserindo espaços e faltando newline final
![image](https://user-images.githubusercontent.com/1651447/150044380-d46c9a76-90ff-4edd-ac39-62e9722042df.png)

**Comment by elpbatista** [comment]
La solución que yo encontré para hacerlo en Postgres, ver código adjunto (está en las funciones de la API), fue crear las features individualmente como GeoJSON y empaquetarlas en un array que sería el valor de “features” en la FeatureCollection (nivel superior de GeoJSON)

Los espacios en blanco y los saltos de línea raros es culpa de ST_AsGeoJSON que usada de ese modo como está en su función ST_AsGeoJSONb, intenta escribir una cadena legible por humanos. Eso se corrige con un parámetro en las opciones (creo recordar) o usando la función ST_AsGeoJSON de este otro modo como se muestra en el código.


 -- +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-- Full Text Search Bounded
-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-- FUNCTION: api.search_bounded(text, numeric[], integer)
-- DROP FUNCTION IF EXISTS api.search_bounded(text, numeric[], integer);
CREATE OR REPLACE FUNCTION api.search_bounded(
    _q text,
    viewbox numeric [],
    lim integer DEFAULT 100
  ) RETURNS json LANGUAGE 'sql' COST 100 IMMUTABLE PARALLEL UNSAFE AS $BODY$ WITH q AS (
    SELECT *,
      (
        (lower(_q) <->spq) + (lower(_q) <->(properties->>'address')::text) + (
          lower(_q) <->(properties->>'display_name')::text
        )
      ) / 3 AS diff
    FROM (
        SELECT *
        FROM api.search
        WHERE ST_Contains(
            ST_SetSRID(
              api.viewbox_to_polygon(viewbox [1], viewbox [2], viewbox [3], viewbox [4]),
              4326
            ),
            geom
          )
      ) q
    ORDER BY diff
    LIMIT lim
  )
SELECT json_build_object(
    'type',
    'FeatureCollection',
    'query',
    _q,
    'features',
    j.features
  ) AS response
FROM (
    SELECT json_agg(ST_AsGeoJSON(r, 'geom', 6)::json) AS features
    FROM (
        SELECT s.geom,
          1 - s.diff AS similarity,
          s.properties->>'_id' AS _id,
          s.properties->>'address' AS address,
          s.properties->>'display_name' AS display_name,
          s.properties->>'barrio' AS barrio,
          s.properties->>'comuna' AS comuna,
          s.properties->>'municipality' AS municipality,
          s.properties->>'divipola' AS divipola,
          s.properties->>'country' AS country
        FROM (
            SELECT *
            FROM q
            WHERE q.diff < (
                SELECT MIN(diff) + MIN(diff) / 10 AND q.diff <.85
                FROM q
              )
          ) s
      ) r
  ) j $BODY$;
ALTER FUNCTION api.search_bounded(text, numeric [], integer) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION api.search_bounded(text, numeric [], integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION api.search_bounded(text, numeric [], integer) TO batista;
GRANT EXECUTE ON FUNCTION api.search_bounded(text, numeric [], integer) TO postgres;

**Comment by 0e1** [comment]
Ordenação ajustada para BH feita em https://github.com/digital-guard/preserv/commit/ff50e68927a27cc04b31d8ed546c03f464e0ae9d e https://github.com/digital-guard/preserv/commit/1f1d6b665e4b7a952bd168940a4f981fb3ae62c4.

Nova linha (e também remoção onde é necessário) na regex https://github.com/AddressForAll/pg_pubLib-v1/blob/main/src/pubLib03-json.sql#L170.

**Comment by 0e1** [comment]
Foi implementado opção para gerar mosaico sem espaços e quebras de linha. Ver [publicação](https://github.com/digital-guard/preserv/wiki/Testes-com-ingest99#publica%C3%A7%C3%A3o).

A opção `pretty_opt=3` faz a função [jsonb_pretty_lines](https://github.com/AddressForAll/pg_pubLib-v1/blob/main/src/pubLib03-json.sql#L166) remover espaços e quebras de linha (Até então, os mosaicos eram gerados com pretty_opt=2). Essa opção não afeta a geração dos arquivos _pts*_.

Exemplo de mosaico geojson gerado com essa opção: [_pk0004.01/geoaddress/geohahes.geojson](https://raw.githubusercontent.com/digital-guard/preservCutGeo-BR2021/main/data/_pk0004.01/geoaddress/geohahes.geojson).

**Comment by 0e1** [comment]
Considero essa issue encerrada. Reabrir se julgar necessário.
