### ISSUE TITLE
SRID de Porto Alegre não cadastrada

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv#55]
Fiz o procedimento de criação de banco de dados intesgt20.
Fiz os comandos na pasta /var/gits/_dg/preserv-BR/data/RS/PortoAlegre/_pk0018.01
make me pg_dbingest=ingest20
make all_layers pg_dbingest=ingest20

Files: 8
Size:       18467884
Compressed: 7306124
Conferindo se SRID 952013 esta configurado:
 srid | proj4text 
------+-----------
(0 rows)

**Comment by 0e1** [comment]
Lembrar que quando se está em preserv-BR/data o formato correto é

`make target pg_db=ingest20`

**Comment by 0e1** [comment]
srid_proj='+proj=tmerc +lat_0=0 +lon_0=-51 +k=0.999995 +x_0=300000 +y_0=5000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs'

**Comment by 0e1** [comment]
https://github.com/digital-guard/preserv-BR/commit/41ced9241a72f017dde411b9f455cb73415fda29

**Comment by 0e1** [comment]
No commit  implementei o caso de srid_proj. Quando srid_proj estiver presente, no caso de um shapefile, shp2pgsql é executado sem a opção -s:

cd $(sandbox); shp2pgsql -D    "NRO_IMOVEL.shp" pk7600001801101_p1_geoaddress | psql -q $(pg_uri_db) 2> /dev/null

E o valor de srid_proj é passado para any_load, por exemplo:

SELECT ingest.any_load('shp2sql','$(sandbox)/NRO_IMOVEL.shp','geoaddress_none','pk7600001801101_p1_geoaddress','7600001801101','fbc62efdbd0f16a7db03b5b775c50c9425367a8dee8a85d9b53e4475bbdb99d2.zip',array['gid', 'textstring AS house_number', 'setor', 'last_edi_1 AS dateModified', 'geom'],'geom',true,'+proj=tmerc +lat_0=0 +lon_0=-51 +k=0.999995 +x_0=300000 +y_0=5000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs')".

Assim, a any_load utilizará o valor em

**Comment by 0e1** [comment]
No commit https://github.com/digital-guard/preserv/commit/ba9ec2f7101bf288b9d0c83d66ff8d0eaf611c3a  implementei o caso de `srid_proj`. Quando `srid_proj` estiver presente, no caso de um shapefile, `shp2pgsql` é executado sem a opção `-s`:

`cd $(sandbox); shp2pgsql -D    "NRO_IMOVEL.shp" pk7600001801101_p1_geoaddress | psql -q $(pg_uri_db) 2> /dev/null`

E o valor de `srid_proj` é passado para `any_load`, por exemplo:

`SELECT ingest.any_load('shp2sql','$(sandbox)/NRO_IMOVEL.shp','geoaddress_none','pk7600001801101_p1_geoaddress','7600001801101','fbc62efdbd0f16a7db03b5b775c50c9425367a8dee8a85d9b53e4475bbdb99d2.zip',array['gid', 'textstring AS house_number', 'setor', 'last_edi_1 AS dateModified', 'geom'],'geom',true,'+proj=tmerc +lat_0=0 +lon_0=-51 +k=0.999995 +x_0=300000 +y_0=5000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs')".`

Assim, a `any_load` [utilizará](https://github.com/digital-guard/preserv/blob/main/src/ingest-step1-ini.sql#L778) o valor,  na função [ST_Transform](https://postgis.net/docs/ST_Transform.html), dessa forma:

`WHEN %s AND ST_SRID(geom)!=4326 AND %s THEN ST_Transform(geom,'+proj=tmerc +lat_0=0 +lon_0=-51 +k=0.999995 +x_0=300000 +y_0=5000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs',4326)`


Até aqui parece tudo bem com a forma que foi implementado? Deixar passar algo?


Porém, quando executado

`make geoaddress pg_db=ingest99`

Obtem-se:

`
NOTICE:  Coordinate values were coerced into range [-180 -90, 180 90] for GEOGRAPHY`

e

`ERROR:  Geohash requires inputs in decimal degrees, got (277140 1.67607e+06, 277146 1.67608e+06).`


Isso indica problemas na transformação de SRID?



Saída completa (apenas o principal)

```
------------------------------------------
------ Layer tipo geoaddress_none  ------
-- Incluindo dados do arquivo-1 do package-7600001801101 na base ingest99 --
 Nome-hash do arquivo-1: fbc62efdbd0f16a7db03b5b775c50c9425367a8dee8a85d9b53e4475bbdb99d2.zip
 Tabela do layer: pk7600001801101_p1_geoaddress
 Sub-arquivos do arquivo-1 com o conteúdo alvo: *NRO_IMOVEL*
 Tema dos sub-arquivos: Imóveis
Run with tmux and sudo! (DANGER: seems not idempotent on psql)
claiton
Above user is root? If not, you have permissions for all paths?
 [press ENTER for yes else ^C]
psql postgres://postgres@localhost/ingest99 -c "DROP TABLE IF EXISTS pk7600001801101_p1_geoaddress CASCADE"
DROP TABLE
Extracting ....
cd /tmp/sandbox/_pkBR181_001; 7z  x -y /var/www/preserv.addressforall.org/download/fbc62efdbd0f16a7db03b5b775c50c9425367a8dee8a85d9b53e4475bbdb99d2.zip "*NRO_IMOVEL*" ; chmod -R a+rwx . > /dev/null

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=C.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (406F1),ASM,AES-NI)

Scanning the drive for archives:
1 file, 13959059 bytes (14 MiB)                       

Extracting archive: /var/www/preserv.addressforall.org/download/fbc62efdbd0f16a7db03b5b775c50c9425367a8dee8a85d9b53e4475bbdb99d2.zip
--
Path = /var/www/preserv.addressforall.org/download/fbc62efdbd0f16a7db03b5b775c50c9425367a8dee8a85d9b53e4475bbdb99d2.zip
Type = zip
Physical Size = 13959059

Everything is Ok       

Files: 8
Size:       230560391
Compressed: 13959059
SRID configurado via PROJ.4 string:
+proj=tmerc +lat_0=0 +lon_0=-51 +k=0.999995 +x_0=300000 +y_0=5000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
Tudo bem até aqui?  [ENTER para continuar ou ^C para sair]

Executando shp2pgsql ...
cd /tmp/sandbox/_pkBR181_001; shp2pgsql -D    "NRO_IMOVEL.shp" pk7600001801101_p1_geoaddress | psql -q postgres://postgres@localhost/ingest99 2> /dev/null
Field featureid is an FTDouble with width 10 and precision 0
Field zorder is an FTDouble with width 10 and precision 0
Field annotation is an FTDouble with width 10 and precision 0
Field symbolid is an FTDouble with width 10 and precision 0
Field fontsize is an FTDouble with width 19 and precision 11
Field xoffset is an FTDouble with width 19 and precision 11
Field yoffset is an FTDouble with width 19 and precision 11
Field angle is an FTDouble with width 19 and precision 11
Field fontleadin is an FTDouble with width 19 and precision 11
Field wordspacin is an FTDouble with width 19 and precision 11
Field characterw is an FTDouble with width 19 and precision 11
Field characters is an FTDouble with width 19 and precision 11
Field flipangle is an FTDouble with width 19 and precision 11
Field override is an FTDouble with width 10 and precision 0
Field setor is an FTDouble with width 10 and precision 0
Field quarteirao is an FTDouble with width 10 and precision 0
Field shape_area is an FTDouble with width 19 and precision 11
Field shape_len is an FTDouble with width 19 and precision 11
Shapefile type: Polygon
Postgis type: MULTIPOLYGON[2]
                             addgeometrycolumn                              
----------------------------------------------------------------------------
 public.pk7600001801101_p1_geoaddress.geom SRID:0 TYPE:MULTIPOLYGON DIMS:2 
(1 row)

psql postgres://postgres@localhost/ingest99 -c "SELECT ingest.any_load('shp2sql','/tmp/sandbox/_pkBR181_001/NRO_IMOVEL.shp','geoaddress_none','pk7600001801101_p1_geoaddress','7600001801101','fbc62efdbd0f16a7db03b5b775c50c9425367a8dee8a85d9b53e4475bbdb99d2.zip',array['gid', 'textstring AS house_number', 'setor', 'last_edi_1 AS dateModified', 'geom'],'geom',true,'+proj=tmerc +lat_0=0 +lon_0=-51 +k=0.999995 +x_0=300000 +y_0=5000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs')"

NOTICE:  Coordinate values were coerced into range [-180 -90, 180 90] for GEOGRAPHY
NOTICE:  Coordinate values were coerced into range [-180 -90, 180 90] for GEOGRAPHY
NOTICE:  Coordinate values were coerced into range [-180 -90, 180 90] for GEOGRAPHY

...

NOTICE:  Coordinate values were coerced into range [-180 -90, 180 90] for GEOGRAPHY
NOTICE:  Coordinate values were coerced into range [-180 -90, 180 90] for GEOGRAPHY
NOTICE:  Coordinate values were coerced into range [-180 -90, 180 90] for GEOGRAPHY
ERROR:  Geohash requires inputs in decimal degrees, got (277140 1.67607e+06, 277146 1.67608e+06).
CONTEXT:  SQL function "feature_asis_geohashes" statement 1
SQL function "feature_asis_assign" statement 1
SQL statement "UPDATE ingest.donated_PackComponent
    SET proc_step=2,   -- if insert process occurs after q_query.
        feature_asis_summary= ingest.feature_asis_assign(q_file_id)
    WHERE id=q_file_id"
PL/pgSQL function ingest.any_load(text,text,text,text,bigint,text,text[],text,boolean,text) line 114 at SQL statement
make: *** [makefile:65: geoaddress] Error 1
```

**Comment by 0e1** [comment]
Implementado em https://github.com/digital-guard/preserv/commit/d657d3c601e5aa8839584fd6e57f135e71b964f0.

Para cada `make me pg_db=ingestXX` executado um número arbitrário é [gerado](https://github.com/digital-guard/preserv/blob/main/src/ingest-step1-ini.sql#L1406) para ser um SRID .

Assim, para cada layer,  o novo SRID é [inserido](https://github.com/digital-guard/preserv/blob/main/src/maketemplates/common003_shp2pgsql.mustache#L2) em `spatial_ref_sys` antes e [removido](https://github.com/digital-guard/preserv/blob/main/src/maketemplates/common001_pgAny_load.mustache#L21) depois do processo de ingestão.

@crebollobr, para utilizar o que foi implementado você precisa dropar e recriar a base ingest que está utilizando em seus testes.
