### ISSUE TITLE
erro no make join de Niteroi

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv#56]
Novo banco de dados ingest20
executei os comandos

make me pg_dbingest=ingest20
make all_layers pg_dbingest=ingest20
make all_joins pg_dbingest=ingest20
esse ultimo deu problema

psql postgres://postgres@localhost/ingest1 -c "SELECT ingest.join('parcel_ext','tx_insct','4bde69d0057c0785598f98963fdae3dc90420fb8f163652d70b659210da0ae2b.zip','cadparcel_cmpl','tx_insctec','39d34950c7c61a89cfc2b4d70b0b34a85b346b41741331009205de0f06c86805.zip')"
ERROR:  too few arguments for format()
CONTEXT:  PL/pgSQL function ingest."join"(text,text,text,text,text,text) line 7 at assignment
make: *** [makefile:192: join-parcel] Error 1

**Comment by 0e1** [comment]
Um %s comentado em um format é tratado como parametro. Esse foi o bug.
Removi os comentarios em [820e7bb92f433b005e1666200777fee5fda162b3](https://github.com/digital-guard/preserv/commit/820e7bb92f433b005e1666200777fee5fda162b3).

Agora, join ok.

**Comment by ppKrauss** [comment]
@crebollobr se sucesso, lembrar de fechar a issue
