### ISSUE TITLE
make de Contagem

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv#57]
Teste no banco de dados novo ingest20

pasta /var/gits/_dg/preserv-BR/data/MG/Contagem/_pk0009.01
comandos

make me pg_dbingest=ingest20
make all_layers pg_dbingest=ingest20

Executando ogr2ogr ...
sudo docker run --rm --network host -v /tmp/sandbox/_pkBR91_001:/tmp osgeo/gdal ogr2ogr -lco GEOMETRY_NAME=geom -overwrite -f "PostgreSQL" PG:" dbname='ingest1' host='localhost' port='5432' user='postgres' " "/tmp/OpenStreetMap.gdb" Logradouros -nln pk7600000901101_p1_via
psql postgres://postgres@localhost/ingest1 -c "CREATE VIEW vw1_pk7600000901101_p1_via AS SELECT OBJECTID AS gid, TIPO_LOGRA || ' ' || NOME_LOGRA AS via_name, geom FROM pk7600000901101_p1_via"
CREATE VIEW
psql postgres://postgres@localhost/ingest1 -c "SELECT ingest.any_load('gdb2sql','/tmp/sandbox/_pkBR91_001/OpenStreetMap.gdb/timestamps','via_full','vw1_pk7600000901101_p1_via','7600000901101','058a6022054e8b3f9ba81f25f7511b58cbd4ad616b0510033b917f3f7f9f23d5.rar',array[]::text[])"
ERROR:  field name must not be null
CONTEXT:  SQL function "feature_asis_geohashes" statement 1
SQL function "feature_asis_assign" statement 1
SQL statement "UPDATE ingest.donated_PackComponent
    SET proc_step=2,   -- if insert process occurs after q_query.
        feature_asis_summary= ingest.feature_asis_assign(q_file_id)
    WHERE id=q_file_id"
PL/pgSQL function ingest.any_load(text,text,text,text,bigint,text,text[],text,boolean) line 109 at SQL statement
make: *** [makefile:201: via] Error 1

**Comment by ppKrauss** [comment]
@crebollobr  por favor não perder tempo nem criar issues enquanto não tiver sinal verde do Claiton e testes básicos no makefile.

**Comment by 0e1** [comment]
Alterações recentes em funções relacionadas ao contexto, parecem ter resolvido esse problema.
Testei e todos os layers de Contagem formam ingeridos.

Recrie a base de dados e teste novamente.

Aqui o passo a passo: https://github.com/digital-guard/preserv/wiki/Testes-reais-para-garantia-de-software-no-servidor-produtivo/


Aqui teste de publicação dos dados de Contagem (via e geoaddress): https://github.com/digital-guard/preservCutGeo-BR2021/tree/main/data/MG/Contagem/_pk0009.01

**Comment by 0e1** [comment]
Issue equivalente e mais atual em issue digital-guard/preserv-BR#44.

**Comment by 0e1** [comment]
Deixando registrado que problemas relacionados à

```
ERROR:  field name must not be null
CONTEXT:  SQL function "feature_asis_geohashes" statement 1
```
estão relacionados à geometrias vazias. Tais geometrias não são mais ingeridas, após o uso de [ST_IsEmpty](https://postgis.net/docs/ST_IsEmpty.html) no processo de ingestão. Ver https://github.com/digital-guard/preserv/issues/80#issuecomment-1032111961.
