### ISSUE TITLE
make de São Paulo

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv#58]
teste no banco de dados novo ingest20
pasta /var/gits/_dg/preserv-BR/data/SP/SaoPaulo/_pk0033.01
comandos
make me pg_dbingest=ingest20
make all_layers pg_dbingest=ingest20

esse ultimo deu erro

make: *** No rule to make target '/var/www/preserv.addressforall.org/download/bae2054448855305db0fc855d2852cd5a7b369481cc03aeb809a0c3c162a2c04.zip', needed by 'parcel'.  Stop.

**Comment by 0e1** [comment]
Bem, se não tem, significa que o arquivo bae2054448855305db0fc855d2852cd5a7b369481cc03aeb809a0c3c162a2c04.zip não está no diretório /var/www/preserv.addressforall.org/download/

Isso quer dizer que esse é um arquivo que está na nuvem, no sharepoint.

Pra fazer o download:

wget dl.digital-guard.org/bae2054448855305db0fc855d2852cd5a7b369481cc03aeb809a0c3c162a2c04.zip

**Comment by 0e1** [comment]
Novamente lembro que é:

```
make me pg_db=ingest20
make all_layers pg_db=ingest20
```

**Comment by 0e1** [comment]
Nesse caso tente usar:

```
wget dl.digital-guard.org/bae2054448855305db0fc855d2852cd5a7b369481cc03aeb809a0c3c162a2c04.zip

make me pg_db=ingestXX

make parcel orig=</pasta/contem/arquivo/baixado> pg_db=ingestXX
```

**Comment by ppKrauss** [comment]
@0e1  por favor iniciar documentação. Neste caso dos downloads, faltou também  indicar em qual pasta fazer o `wget -P`

**Comment by 0e1** [comment]
> @0e1 por favor iniciar [documentação](https://github.com/digital-guard/preserv/tree/main/docs/pt). Neste caso dos downloads, faltou também indicar em qual pasta fazer o `wget -P`

Comentário editado.

Documentação iniciada em https://github.com/digital-guard/preserv/blob/main/docs/pt/man-diversos.md.
