### ISSUE TITLE
Adaptar e instruir como será o novo make

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#6]
Após a decisão de efetuar git-ignore sobre os makefiles, `data/**/makefile`, por exemplo em  [preserv-BR](https://github.com/digital-guard/preserv-BR), ficou pendente o recurso para rodar `make me` e gerar o makefile. 
Ficou pendente também (em [suporte/issue9](https://github.com/AddressForAll/suporte/issues/9)) decidir se o [git preserv](https://github.com/digital-guard/preserv) será incluso em preserv-BR como submódulo (se isso for simples) ou não.

O *path*  absoluto do preserv é `/opt/gits/_dg/preserv`  de modo que o python e outros arquivos podem ser solicitados sem necessidade de submódulo ou outro tipo de cópia.

O importante é o usuário poder rodar um comando `makeMe_onAll.sh` do preserv  que faça scan e copie em todas as pastas de pacotes um arquivo `makefile` incial com para poder rodar `make me`.

**Comment by ppKrauss** [comment]
@cchness , quanto ao uso do `/opt/gits` como pasta para uso pessoal ou no servidor, de clonagem e make dos scripts...  É razoável manter em `/opt/` ou seria melhor em `/var`? ou ainda em `/etc`?

**Comment by cchness** [comment]
Tomando como referencia https://www.pathname.com/fhs/pub/fhs-2.3.html#THEROOTFILESYSTEM, eu colocaria em /srv ou ainda em /var. E não misturaria esses dados com configurações da máquina em /etc.

**Comment by ppKrauss** [comment]
Fechado no preserv-BR com https://github.com/digital-guard/preserv-BR/commit/d55e269c0a02a0faef84c37a5373a6602c0793ee

Agora falta resolver a [diretiva para cópias locais comentada acima](https://github.com/digital-guard/preserv/issues/6#issuecomment-915505689)

**Comment by ppKrauss** [comment]
@0e1 , marcar com Carlos data para transição no servidor, de /opt/gits para /var/gits
