### ISSUE TITLE
ERROR: file-read problem or data ingested before

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#60]
Usando `make` em contexto de inicializalçao prévia. Talvez seja apenas um bug de interface, ou seja, diz que é ERRO mas na verdade os dados já foram criados antes. Se for apenas isso, o ideal é avisar como fazer o DELETE (ou target para isso).

`user@oficalNews2018:/var/gits/_dg/preserv-BR/data/AC/RioBranco/_pk0042.01$ make all_layers`

## Dump e contexto

```
...
Tudo bem até aqui?  [ENTER para continuar ou ^C para rodar WS/ingest-step1]

Executando shp2pgsql ...
cd /tmp/sandbox/_pkBR421_001; shp2pgsql -D   -s 32719 "logradouros.shp" pk7600004201301_p3_via | psql -q postgres://postgres@localhost/ingest1 2> /dev/null
Shapefile type: Arc
Postgis type: MULTILINESTRING[2]
                             addgeometrycolumn                              
----------------------------------------------------------------------------
 public.pk7600004201301_p3_via.geom SRID:32719 TYPE:MULTILINESTRING DIMS:2 
(1 row)

psql postgres://postgres@localhost/ingest1 -c "CREATE VIEW vw3_pk7600004201301_p3_via AS SELECT gid, Nome ||' '|| tipo AS via_name,  geom FROM pk7600004201301_p3_via"
CREATE VIEW
psql postgres://postgres@localhost/ingest1 -c "SELECT ingest.any_load('shp2sql','/tmp/sandbox/_pkBR421_001/logradouros.shp','via_full','vw3_pk7600004201301_p3_via','7600004201301','29d68e5ce006079b06b710cc2df3aa08d6cb6934f32bc0b29fc46d3e8272ff77.rar',array[]::text[])"
                                             any_load                                             
--------------------------------------------------------------------------------------------------
 ERROR: file-read problem or data ingested before, see /tmp/sandbox/_pkBR421_001/logradouros.shp.
(1 row)

psql postgres://postgres@localhost/ingest1 -c "DROP VIEW vw3_pk7600004201301_p3_via"
DROP VIEW
Confira os resultados nas tabelas ingest.donated_packcomponent e ingest.feature_asis.
FIM.

**Comment by 0e1** [comment]
> Usando `make` em contexto de inicializalçao prévia. Talvez seja apenas um bug de interface, ou seja, diz que é ERRO mas na verdade os dados já foram criados antes. Se for apenas isso, o ideal é avisar como fazer o DELETE (ou target para isso).

Conforme [any_load](https://github.com/digital-guard/preserv/blob/main/src/ingest-step1-ini.sql#L888), isso acontece quando os dados já haviam sido ingeridos. Dá pra ajustar a mensagem com o [target usado para deletar](https://github.com/digital-guard/preserv/blob/main/src/maketemplates/commomLast.mustache.mk#L93).

**Comment by 0e1** [comment]
Ajustada mensagem. Ver https://github.com/digital-guard/preserv/commit/2f74f9db49c49cfd91b665f1251f0b3668da815d.

**Comment by crebollobr** [comment]
Testado com Porto Alegre

ERROR: file-read problem or data ingested before. See /tmp/sandbox/_pkBR181_001/Bairros_LC12112_16.shp or use make delete_file id= to delete data.

id teria que ter um valor?

**Comment by 0e1** [comment]
Mensagem ajustada. Agora informando o id e view para obter mais detalhes do layer. Exemplo:

```
 ERROR: file-read problem or data ingested before.+
 See /tmp/sandbox/_pkBR291_001/LOTES_PONTO_S2K.shp+
 or use make delete_file id=1 to delete data.     +
 See ingest.vw03full_layer_file.
```
