### ISSUE TITLE
Usar ingest.jplanet_inserts_and_drops

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#61]
Ver https://github.com/digital-guard/preserv/blob/main/src/osm_hstore2jsonb.sql

* o script antes fazia a ingestão
* agora a ingestão deve ser executada em conformidade com o country_id do pacote, via makefile.

**Comment by 0e1** [comment]
Depois de alguns consertos, ainda resta tratar `osm_id` duplicados, como no exemplo de carregamento do arquivo _pbf_:

```
$ /var/gits/_dg/preserv-CO/data/_pk0004.01$ make openstreetmap pg_db=ingest99
cd /tmp/sandbox/_pkCO41_001;  cp  /var/www/preserv.addressforall.org/download/b82a7ab85d2cb4342d51b7ab97e74be291a57c9f35001bf827d1226527449ca2.pbf . ; chmod -R a+rwx . > /dev/null
osm2pgsql -E 4326 -c -d ingest99 -U postgres -H localhost --slim --hstore --extra-attributes --hstore-add-index --multi-geometry --number-processes 4 --style /usr/share/osm2pgsql/empty.style /tmp/sandbox/_pkCO41_001/b82a7ab85d2cb4342d51b7ab97e74be291a57c9f35001bf827d1226527449ca2.pbf
osm2pgsql version 1.2.1 (64 bit id space)


...


Osm2pgsql took 347s overall
node cache: stored: 29619433(100.00%), storage efficiency: 50.43% (dense blocks: 183, sparse nodes: 28614424), hit rate: 100.00%
Convertendo hstore para jsonb
psql postgres://postgres@localhost/ingest99 -c "SELECT ingest.jplanet_inserts_and_drops(170::smallint,true);"
ERROR:  duplicate key value violates unique constraint "jplanet_osm_roads_pkey"
DETAIL:  Key (osm_id)=(-114574) already exists.
CONTEXT:  SQL statement "INSERT INTO jplanet_osm_roads
    SELECT p_country_id, osm_id, z_order,
       jsonb_strip_nulls( lib.osm_to_jsonb(tags), true ) as tags,
       way
    FROM planet_osm_roads"
PL/pgSQL function ingest.jplanet_inserts_and_drops(smallint,boolean) line 21 at SQL statement
make: *** [makefile:112: openstreetmap] Error 1
```

**Comment by ppKrauss** [comment]
> Depois de alguns consertos, ainda resta decidir como tratar `osm_id` duplicados, como no exemplo de carregamento do arquivo _pbf_:

o OSM é uma ingestão muito especial, e podemos ser mais exigentes... Eu nunca vi o PBF duplicar objetos, precisamos entender melhor o que ocorreu... Nesse caso a função não pode fazer DROP do planet_osm_roads original para conferirmos se a falha teve origem nele ou em nossas funções.  Se por acaso for bug OSM, `DO NOTHING` resolve e o INSERT segue.

**Comment by 0e1** [comment]
No pbf não parece ter problemas. Nele, um id por elemento. Já nas tabelas produzidas pelo `osm2pgsql` não há uma linha por elemento.
O que me parece é: o `osm2pgsql` não garante uma linha por elemento nas tabelas que ele produz, mesmo usando o `--multi-geometry`. Então, não dá pra usar `osm_id` como chave primária, sem antes garantir que não há duplicatas. A diferença entre as linhas com `osm_id` iguais é a geometria. Daria para agrupar por `osm_id` unindo as geometrias. Por hora, o efeito do `DO NOTHING` é inserir apenas parte da geometria de elementos que utilizam mais de uma linha nas tabelas produzidas pelo `osm2pgsql`. E, pelo que entendo, vias muito longas podem ocupar mais de uma linhas nas tabelas do `osm2pgsql`.

**Comment by 0e1** [comment]
Conforme http://download.geofabrik.de/technical.html os dados são extraídos utilizando um poligono que não representa exatamente as fronteiras de um país.
Assim, recortes de países vizinhos podem ter dados em comum.
Essa situação foi contornada usando `PRIMARY KEY(country_id, osm_id)`. Para evitar que um dado fora das fronteiras de um país seja ingerido como se estivesse nele, foi usado ST_Intersection com a geometria do país no momento da ingestão.
