### ISSUE TITLE
Publicar propriedades padronizadas e específicas do layer 

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#63]
A cada tipo de layer apresentar as propriedades conforme padrão. No caso do layer *via*  os atrinutos são `name` e (raramente) `ref`. ... Por hora o que apresenta, `address`, é um resquício do *geoaddress*.

![image](https://user-images.githubusercontent.com/1651447/150715136-efec1742-cb44-44f1-b49b-25756bd022b2.png)
Ver https://github.com/digital-guard/preservCutGeo-BR2021/blob/main/data/AC/_pk0042.01/via/pts_6qpz.geojson

ou https://github.com/digital-guard/preservCutGeo-BR2021/blob/main/data/_pk0004.01/via/pts_6f.geojson

PS: outro problema é que *via* não deveria apresentar pontos, só linhas.

**Comment by 0e1** [comment]
Pelo meu entendimento, atualmente, as _properties_ padronizadas para cada [ftype](https://github.com/digital-guard/preserv/blob/main/docs/pt/ftypes.md) estão sendo consideradas pela função [ingest.feature_asis_export(p_file_id bigint)](https://github.com/digital-guard/preserv/blob/main/src/ingest-step1-ini.sql#L1611) que prepara os dados para publicação, podendo a issue ser fechada.

Issue relacionada a esse assunto: https://github.com/digital-guard/preserv/issues/95
