### ISSUE TITLE
falha no make ao chamar ingest.any_load

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#70]
* Outro bug: falta a publicação de poligonos. apesar do make oferecer "all_layers via block nsvia parcel", o  `make publicating_geojsons_block`  resultou na mensagem "make: *** No rule to make target 'publicating_geojsons_block'.  Stop."

* Outro bug: publicando apenas null. more /tmp/sandbox/_pkBR421_001/BR/data/AC/RioBranco/_pk0042.03/via/geohashes.geojson
{"type":"FeatureCollection","features":null}

* decidir qual view usar na listagem, `select * from ingest.vw08info_packcomponent`  ou adaptação de `ingest.vw04simple_layer_file`

----

```
user@oficalNews2018:/var/gits/_dg/preserv-BR/data/PR/Pinhais/_pk0014.01$ **make all_layers**
...

psql postgres://postgres@localhost/ingest1 -c "SELECT ingest.any_load('shp2sql','/tmp/sandbox/_pkBR141_001/RUAS.shp','via_full','pk7600001401201_p2_via','7600001401201','27c0c467222a668837f62e9f40ac85f94685ea50f3d655207384f2343d13f573.rar',array['gid', 'nome_rua AS via_name', 'geom'],)"
ERROR:  syntax error at or near ")"
LINE 1: ...3d13f573.rar',array['gid', 'nome_rua AS via_name', 'geom'],)
                                                                      ^
make: *** [makefile:151: via] Error 1


```

**Comment by 0e1** [comment]
> * Outro bug: falta a publicação de poligonos. apesar do make oferecer "all_layers via block nsvia parcel", o  `make publicating_geojsons_block`  resultou na mensagem "make: *** No rule to make target 'publicating_geojsons_block'.  Stop."

Não tem porque em [make_ref027a.mustache.mk#L127](https://github.com/digital-guard/preserv/blob/main/src/maketemplates/make_ref027a.mustache.mk#L127) o target está presente apenas para `geoaddress` e `via`. E está apenas para esses dois pois em [ingest.feature_asis_export](https://github.com/digital-guard/preserv/blob/main/src/ingest-step1-ini.sql#L1139) apenas esses dois estão presentes no `case`.
Então: 
- adicionar no case
- adicionar no template.

> * Outro bug: publicando apenas null. more /tmp/sandbox/_pkBR421_001/BR/data/AC/RioBranco/_pk0042.03/via/geohashes.geojson
{"type":"FeatureCollection","features":null}
Provavelmente relacionado com https://github.com/digital-guard/preserv/issues/66#issuecomment-1024914513.

**Comment by 0e1** [comment]
> 



> * Outro bug: falta a publicação de poligonos. apesar do make oferecer "all_layers via block nsvia parcel", o  `make publicating_geojsons_block`  resultou na mensagem "make: *** No rule to make target 'publicating_geojsons_block'.  Stop."

Resolvido, todos os layers com geometria possuem target de publicação. Ainda está pendente completar o case, para cada layer: https://github.com/digital-guard/preserv/blob/main/src/ingest-step1-ini.sql#L1136



> * Outro bug: publicando apenas null. more /tmp/sandbox/_pkBR421_001/BR/data/AC/RioBranco/_pk0042.03/via/geohashes.geojson
>       {"type":"FeatureCollection","features":null}

Resolvido, target de publicação ainda não tinha sido atualizado, com o nome dado em https://github.com/digital-guard/preserv/issues/66#issuecomment-1024914513.



> ```
> user@oficalNews2018:/var/gits/_dg/preserv-BR/data/PR/Pinhais/_pk0014.01$ **make all_layers**
> ...
> 
> psql postgres://postgres@localhost/ingest1 -c "SELECT ingest.any_load('shp2sql','/tmp/sandbox/_pkBR141_001/RUAS.shp','via_full','pk7600001401201_p2_via','7600001401201','27c0c467222a668837f62e9f40ac85f94685ea50f3d655207384f2343d13f573.rar',array['gid', 'nome_rua AS via_name', 'geom'],)"
> ERROR:  syntax error at or near ")"
> LINE 1: ...3d13f573.rar',array['gid', 'nome_rua AS via_name', 'geom'],)
>                                                                       ^
> make: *** [makefile:151: via] Error 1
> ```

Isso significa que a base ingest utilizada não está usando hcode_parameters. Com base ingest atualizada, esse problema não existe.

**Comment by ppKrauss** [comment]
ok, parece tudo resolvido.
