### ISSUE TITLE
Reduzir jurisdiction_geom e criar views

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#72]
As tabelas `ingest.fdw_foreign_jurisdiction_geom` (base Ingest) e `optim.jurisdiction_geom` (base DL03) podem ser VIEWs, de JOIN com jurisdiction e uma tabela jurisdiction_geom mais simples:
```sql
CREATE  TABLE x.jurisdiction_geom (
   osm_id bigint, 
   isolabel_ext text, 
  geom geometry(Geometry,4326),
  kx_ghs1_intersects text[],
  kx_ghs2_intersects text[]
)...
```
As colunas de `kx_` serão utilizadas apenas na API para otimizar buscas e resolução de geocódigos, então por hora não precisamos delas nas FDWs de ingest.

**Comment by 0e1** [comment]
De acordo. 
Em DL03t_main:
`optim.jurisdiction` (adaptando no que for possível à nova estrutura que está proposta e comentada no código)
`optim.jurisdiction_geom` (simplificada)

Em ingestXX:
```
ingest.fdw_jurisdiction
ingest.fdw_jurisdiction_geom
ingest.vwxx_fulljurisdiction
```

Essa alteração exigirá que todas as bases _ingest_ utilizadas atualmente sejam recriadas. Então, aguardemos o momento oportuno pra fazer isso.

**Comment by 0e1** [comment]
Mudança implantada. As colunas de `kx_` foram mantidas no fdw, pensando em facilitar qualquer futura mudança.
