### ISSUE TITLE
Simplificar CREATE VIEW do Mustache

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#78]
Tendo em vista que o código agora se encontra mais maduro e estável, convém criar funções no schema `ingest` (ou `lib`)  para simplificar as views de https://github.com/digital-guard/preserv/blob/main/src/maketemplates/common008_publicating_geojsons.mustache

**Comment by 0e1** [comment]
Processo simplificado, o código foi absorvido pela função ingest.publicating_geojsons_p5.
