### ISSUE TITLE
Prioridades da semana 2021.

### ISSUE THREAD

**Issue by 0e1** [digital-guard/preserv#8]
Para antes do dia 8/10:

1 - Florianópolis;
2 - São Paulo;
3 - Colombia;
4 - Joins;
5 - Onedrive/sha256

**Comment by ppKrauss** [comment]
Quais resolvidos?  Indicar também as pendências associadas: 
* ingest CSV, com cadvia ou address de https://github.com/AddressForAll/WS/blob/master/src/ingest-step1-ini.sql#L171
* UNION = multi-shape
* ...

**Comment by ppKrauss** [comment]
@0e1 podemos fechar essa issue, tudo resolvido?

**Comment by 0e1** [comment]
Sim. Todas resolvidas.
