### ISSUE TITLE
Filtragem de "poeira" e geometrias inválidas

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#80]
Durante a ingestão é importante descartar geometrias inválidas, para garantir que o custo de revisão das geometrias problemáticas fique por conta do fornecedor (envia mais tarde uma segunda versão dos dados). A tabela `ingest.feature_asis`  portanto não deveria conter "dados muito ruins".

Alguns critérios são óbvios, outros requerem discussão para decidirmos sua implementação:

1. IS NOT NULL
2. [ST_IsSimple](https://postgis.net/docs/ST_IsSimple.html) e [ST_IsValid](https://postgis.net/docs/ST_IsValid.html), ver https://stackoverflow.com/a/58587330/287948
3. As geometrias de dimensão superior a zero não podem ser nem conter  "poeira" ou  ["buracos de contrabando"](https://gis.stackexchange.com/q/90804/7505), ou seja, possuem dimensão superior ao erro estipulado. Por exemplo os polígonos, mesmo relativos a *parcel* precisam ter área mínima, de por exemplo 5 m2.
4. Geometrias internas à jurisdição. Por exemplo o material Geofabrick do Brasil que é incluso por segurança para além da fronteira, precisa ser descartado. Um ponto de endereço da cidade X não pode estar contido na jurisdição Y. <br/> PS: o caso de  *parcel* (ex. condomínios horizontais e fazendas) é mais complexo. Ao contrário das jurisdições globais (país), a demanda por separação em escala maior (ex. municipal) é menos rígida. Estando na na fronteira, por _default_ recortamos *parcel* conforme interseção da jurisdição. A parte que ficou de fora é também jurisdição da  cidade vizinha, precisamos avaliar como garantir que a inclusão completa ocorra. Idem estradas municipais e trechos federais, segmentados por jurisdição. 

---

Indicar aqui nesta *issue* as decisões finais e fechar a *issue* quando todas estiverem implementadas nas funções de ingestão, em particular `ingest.any_load`.

**Comment by 0e1** [comment]
Talvez devêssemos acrescentar mais um critério:

5. [ST_IsEmpty](https://postgis.net/docs/ST_IsEmpty.html)

Erros do tipo:

```
ERROR:  field name must not be null
CONTEXT:  SQL function "feature_asis_geohashes" statement 1
SQL function "feature_asis_assign_signature" statement 1
SQL statement "UPDATE ingest.donated_PackComponent
    SET proc_step=3,   -- if insert process occurs after q_query.
        lineage =  lineage || ingest.feature_asis_assign_signature(q_file_id)
    WHERE id=q_file_id"
PL/pgSQL function ingest.any_load(text,text,text,text,bigint,text,text[],integer,text,boolean) line 178 at SQL statement
make: *** [makefile:192: parcel] Error 1
```
São ocasionados por geometrias vazias. Quando a geometria é vazia, [ST_GeoHash](https://postgis.net/docs/ST_GeoHash.html) não retorna um _geohash_, ocasionando o erro citado acima.

O erro acima foi retornado por causa dos seguintes _feature_id_ do `parcel` de Rio Branco:
```
 file_id | feature_id |                      properties                      |            geom            | kx_ghs9 | gtype | ghs 
---------+------------+------------------------------------------------------+----------------------------+---------+-------+-----
       6 |      60066 | {"via_name": "RUAMADEREIRA", "house_number": "662"}  | 0103000020E610000000000000 |         | poly  | 
       6 |      62999 | {"via_name": "RUA13 DE MAIO", "house_number": "410"} | 0103000020E610000000000000 |         | poly  | 
       6 |      89718 | {"via_name": "TRVMINEIRO,", "house_number": null}    | 0103000020E610000000000000 |         | poly  | 
```
Aplicando [ST_AsText](https://postgis.net/docs/ST_AsText.html) à geom:

```
SELECT ST_AsText('0103000020E610000000000000');
   st_astext   
---------------
 POLYGON EMPTY
```

**Comment by 0e1** [comment]
O tratamento atual data as geometrias foi descrito em https://github.com/digital-guard/preserv/blob/main/docs/pt/man-diversos.md#resumo-do-tratamento-aplicado-%C3%A0s-geometrias-no-processo-de-ingest%C3%A3o
