### ISSUE TITLE
Ajustar propriedades do mosaicos publicados

### ISSUE THREAD

**Issue by 0e1** [digital-guard/preserv#86]
Propriedades presentes em todos os layers:
- ghs: string, geohash;
- ghs_bytes: inteiro. soma da quantidade de bytes dos itens (SUM(length(St_asGeoJson(geom)));
- ghs_area: duas casa decimais. Área de _ghs_, em km2;
- ghs_len: inteiro. Tamanho de ghs;
- ghs_items: inteiro. Quantidade de itens em ghs;
- ghs_itemsDensity: duas casas decimais. Densidade, ghs_items por ghs_area (itens por unidade de área);
- ghsval_unit: nome da unidade utilizada como métrica da distribuição (_bytes_ ou _ghs_items_);

Propriedade que variam conforme os layers:
- size: duas casas decimais. Tamanho total dos itens no _ghs_;
- size_unit: unidade de _size_;
        dim0 = pontos = não precisa de soma de métrica
        dim1= linhas = tem soma de métrica km
        dim2 = polígonos = tem soma de km2, e densidade_km2
- size_unitDensity: duas casas decimais. Densidade, ghs_bytes por ghs_area (bytes por unidade de área).

**Comment by ppKrauss** [comment]
Parece que missão cumprida!
