### ISSUE TITLE
resolver caso de mistura de layers como o de POA

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#90]
As vias de POA estão misturadas a linhas e polígonos da hidrografia

**Comment by 0e1** [comment]
Olhando os dados, as vias são discriminadas pelo campo `CDIDECAT`.
São 40 categorias diferentes, listadas a seguir. Então, devemos descartar as categorias que não queremos.

De imediato, acho que devemos remover: AR, LAGO, RIO.
Mas precisamos saber o significado de todas para decidir quais utilizar.

@crebollobr temos disponivel uma listagem com os significados das abreviações?

CDIDECAT:

- AC: acesso
- AL: alameda
- **AR**: arroio
- AS:
- AV: avenida
- BC: beco
- BV
- CA
- CICL
- CN
- DIR
- ESC
- ESP
- EST
- ESTR
- GAL
- I
- JAR
- **LAGO**
- LE
- LG
- MER
- PCA: praça
- PRQ
- PSG
- PSL
- R: rua
- **RIO**
- RP
- RTL
- TERM
- TRAV: travessa
- TRVS
- TUN
- VA
- VDT
- VE
- VIA
- VP
- VTC

**Comment by 0e1** [comment]
O menu em http://cdlweb.procempa.com.br/cdlmapafotos/CDLPesquisaLogradouroAvancada.asp possui descrição para as abreviações. Atualizei meu comentário acima.

**Comment by 0e1** [comment]
Lembrete: escrever essas alterações no readme de POA.

**Comment by 0e1** [comment]
Adicionado ao readme.
