### ISSUE TITLE
Implementar o modelo de pontos genéricos

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#91]
Alguns doadores não possuem pontos de endereçamento, mas possuem 

* "pontos de poste": postes da linha de transmissão elétrica das ruas de uma cidade. 
* "marcos geodésicos": pontos para ajuste do GPS, etc. 
* .. outros a classificar. Por exemplo tampas de esgoto, hidrantes, etc.

Esses pontos são em geral mais precisos, portanto ajudam a consolidar os demais dados.

---

Exemplos exóticos: no Chile nos fornecem *pontos de inicio e fim de face de quadra*, ou seja, ao invés da numeração predial, uma interpolação precisa.

**Comment by 0e1** [comment]
Adicionado na documentação em https://wiki.addressforall.org/doc/dg:AsIs_feature_types#Com_geometria
